"use client";

type Row = { id: string; closing_date: string; shift?: string; actual_cash: number; expected_cash: number; variance: number; classification: string; status: string; approval_required?: boolean; variance_reason: string | null };
export function CashClosingReport({ closings, currency }: { closings: Row[]; currency: string }) {
  const shortage = closings.filter((r) => Number(r.variance) < 0).reduce((sum, r) => sum + Math.abs(Number(r.variance)), 0);
  const excess = closings.filter((r) => Number(r.variance) > 0).reduce((sum, r) => sum + Number(r.variance), 0);
  const balanced = closings.filter((r) => Number(r.variance) === 0).length;
  const download = () => {
    const csv = ["Date,Shift,Expected,Actual,Variance,Classification,Status,Reason", ...closings.map((r) => [r.closing_date, r.shift ?? "full_day", r.expected_cash, r.actual_cash, r.variance, r.classification, r.status, JSON.stringify(r.variance_reason ?? "")].join(","))].join("\n");
    const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); a.download = "cash-closings.csv"; a.click(); URL.revokeObjectURL(a.href);
  };
  return <section id="cash-closing-report" className="rounded-card border border-ledger-200 bg-white shadow-sm dark:border-ledger-700 dark:bg-ink-900">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-ledger-100 p-5 dark:border-ledger-800"><div><h2 className="font-semibold text-ink-900 dark:text-white">Daily Cash Closing Report</h2><p className="text-xs text-ledger-500">{closings.length} records · {currency}</p></div><div className="flex gap-2"><button onClick={download} className="rounded-md border border-ledger-200 px-3 py-2 text-xs font-medium hover:bg-ledger-50 dark:border-ledger-700">Download CSV</button><button onClick={() => window.print()} className="rounded-md bg-ink-900 px-3 py-2 text-xs font-medium text-white dark:bg-white dark:text-ink-900">Print Report</button></div></div>
    <div className="grid gap-3 p-5 sm:grid-cols-3"><div className="rounded-lg bg-emerald-50 p-4 dark:bg-emerald-950/30"><p className="text-xs text-emerald-700 dark:text-emerald-300">Balanced Closings</p><p className="mt-1 text-xl font-semibold text-emerald-800 dark:text-emerald-200">{balanced}</p></div><div className="rounded-lg bg-red-50 p-4 dark:bg-red-950/30"><p className="text-xs text-red-700 dark:text-red-300">Shortage Total</p><p className="mt-1 text-xl font-semibold text-red-800 dark:text-red-200">{shortage.toFixed(2)} {currency}</p></div><div className="rounded-lg bg-blue-50 p-4 dark:bg-blue-950/30"><p className="text-xs text-blue-700 dark:text-blue-300">Excess Total</p><p className="mt-1 text-xl font-semibold text-blue-800 dark:text-blue-200">{excess.toFixed(2)} {currency}</p></div></div>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-ledger-50 text-xs text-ledger-500 dark:bg-ink-950"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Shift</th><th className="px-5 py-3 text-right">Expected</th><th className="px-5 py-3 text-right">Actual</th><th className="px-5 py-3 text-right">Variance</th><th className="px-5 py-3">Result</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{closings.map((r) => <tr key={r.id} className="border-t border-ledger-100 dark:border-ledger-800"><td className="px-5 py-3">{r.closing_date}</td><td className="px-5 py-3 capitalize">{(r.shift ?? "full_day").replace("_", " ")}</td><td className="px-5 py-3 text-right">{Number(r.expected_cash).toFixed(2)}</td><td className="px-5 py-3 text-right">{Number(r.actual_cash).toFixed(2)}</td><td className={`px-5 py-3 text-right font-medium ${Number(r.variance) < 0 ? "text-red-600" : "text-emerald-600"}`}>{Number(r.variance).toFixed(2)}</td><td className="px-5 py-3 capitalize">{r.classification}</td><td className="px-5 py-3 capitalize">{r.status.replace("_", " ")}{r.approval_required ? " · approval" : ""}</td></tr>)}</tbody></table></div>
  </section>;
}
