"use client";
import { formatCurrencyAmount, type CurrencyConfig } from "@/lib/currency";

type Row = { id: string; closing_date: string; shift?: string; opening_cash?: number; cash_sales?: number; cash_receipts?: number; cash_refunds?: number; cash_expenses?: number; deposits?: number; withdrawals?: number; actual_cash: number; expected_cash: number; variance: number; classification: string; status: string; approval_required?: boolean; variance_reason: string | null };

export function CashClosingReport({ closings, currency }: { closings: Row[]; currency: CurrencyConfig }) {
  const shortage = closings.filter((r) => Number(r.variance) < 0).reduce((sum, r) => sum + Math.abs(Number(r.variance)), 0);
  const excess = closings.filter((r) => Number(r.variance) > 0).reduce((sum, r) => sum + Number(r.variance), 0);
  const balanced = closings.filter((r) => Number(r.variance) === 0).length;
  const download = () => {
    const csv = ["Date,Shift,Expected,Actual,Variance,Classification,Status,Reason", ...closings.map((r) => [r.closing_date, r.shift ?? "full_day", r.expected_cash, r.actual_cash, r.variance, r.classification, r.status, JSON.stringify(r.variance_reason ?? "")].join(","))].join("\n");
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "cash-closing-report.csv"; link.click(); URL.revokeObjectURL(link.href);
  };
  return <section id="cash-closing-report" className="cash-closing-report rounded-xl border border-[#dce8f2] bg-white shadow-sm dark:border-ledger-700 dark:bg-ink-900">
    <div className="border-b border-[#dce8f2] p-6 print:border-b-2">
      <div className="flex flex-wrap items-start justify-between gap-5">
        <div><div className="mb-2 flex items-center gap-3"><div className="h-9 w-9 rounded-lg bg-[#1478dd]" /><div><p className="text-lg font-bold text-[#12345a]">ThinkSales Pro</p><p className="text-[10px] text-ledger-500">Smarter Business. Greater Growth.</p></div></div><h2 className="mt-5 text-2xl font-bold text-[#12345a] dark:text-white">End of Day Cash Closing Report</h2><p className="mt-1 text-xs text-ledger-500">This report provides a summary of the cash activities for the day, including system calculations and variance analysis.</p></div>
        <div className="grid grid-cols-2 gap-x-8 gap-y-3 rounded-lg bg-[#f0f7fd] p-4 text-xs text-[#31577c]"><span>Closing Date<br /><strong>{closings[0]?.closing_date ?? "—"}</strong></span><span>Branch<br /><strong>Selected Branch</strong></span><span>Shift<br /><strong>{(closings[0]?.shift ?? "full_day").replace("_", " ")}</strong></span><span>Status<br /><strong>{closings[0]?.status?.replace("_", " ") ?? "Not closed"}</strong></span></div>
      </div>
    </div>
    <div className="grid gap-3 p-6 sm:grid-cols-2 lg:grid-cols-5">{[["Opening Cash", closings[0]?.opening_cash ?? 0], ["Total Cash Sales", closings.reduce((s, r) => s + Number(r.cash_sales ?? 0), 0)], ["Cash Receipts", closings.reduce((s, r) => s + Number(r.cash_receipts ?? 0), 0)], ["Cash Expenses", closings.reduce((s, r) => s + Number(r.cash_expenses ?? 0), 0)], ["Deposits / Withdrawals", closings.reduce((s, r) => s + Number(r.deposits ?? 0) + Number(r.withdrawals ?? 0), 0)]].map(([label, value]) => <div key={String(label)} className="rounded-lg border border-[#dce8f2] p-4"><p className="text-[10px] text-ledger-500">{label}</p><p className="mt-2 font-bold text-[#17385d]">{formatCurrencyAmount(Number(value), currency)}</p></div>)}</div>
    <div className="grid gap-4 px-6 pb-6 lg:grid-cols-[1.1fr_1fr_1fr]">
      <div className="rounded-lg border border-[#dce8f2] p-4"><h3 className="mb-4 font-bold text-[#17385d]">Cash Summary</h3>{[["Opening Cash", closings[0]?.opening_cash ?? 0], ["Cash Sales", closings[0]?.cash_sales ?? 0], ["Customer Payments (Cash)", closings[0]?.cash_receipts ?? 0], ["Cash Receipts", closings[0]?.cash_receipts ?? 0], ["Refunds", -(closings[0]?.cash_refunds ?? 0)], ["Cash Expenses", -(closings[0]?.cash_expenses ?? 0)], ["Cash Withdrawals", -(closings[0]?.withdrawals ?? 0)], ["Cash Deposits", -(closings[0]?.deposits ?? 0)]].map(([label, value]) => <div key={String(label)} className="flex justify-between border-b border-[#edf2f7] py-2 text-xs"><span>{label}</span><strong>{formatCurrencyAmount(Number(value), currency)}</strong></div>)}<div className="mt-4 flex justify-between rounded bg-[#edf7ff] p-3 text-sm font-bold text-[#1675d1]"><span>Expected Closing Cash</span><span>{formatCurrencyAmount(Number(closings[0]?.expected_cash ?? 0), currency)}</span></div></div>
      <div className="rounded-lg border border-[#dce8f2] p-4"><h3 className="mb-4 font-bold text-[#17385d]">Cash Count Details</h3><div className="space-y-4 text-xs"><div className="flex justify-between border-b py-3"><span>Notes Count</span><strong>—</strong></div><div className="flex justify-between border-b py-3"><span>Coin Count</span><strong>—</strong></div><div className="flex justify-between rounded bg-[#edf7ff] p-3 font-bold"><span>Total Physical Cash</span><strong>—</strong></div></div></div>
      <div className={`rounded-lg border p-4 ${shortage > 0 ? "border-red-200 bg-red-50" : "border-emerald-200 bg-emerald-50"}`}><h3 className="mb-4 font-bold text-[#17385d]">Variance Status</h3><p className="text-2xl font-bold text-red-500">{formatCurrencyAmount(shortage, currency)}</p><div className="mt-5 space-y-3 text-xs"><div className="flex justify-between"><span>Expected Cash</span><strong>{formatCurrencyAmount(Number(closings[0]?.expected_cash ?? 0), currency)}</strong></div><div className="flex justify-between"><span>Actual Cash</span><strong>{formatCurrencyAmount(Number(closings[0]?.actual_cash ?? 0), currency)}</strong></div><p className="rounded bg-white/70 p-3 text-red-600">A variance has been detected. Review the closing reason and approval status.</p></div></div>
    </div>
    <div className="grid gap-4 px-6 pb-6 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-lg border border-[#dce8f2] p-4"><h3 className="mb-4 font-bold text-[#17385d]">Recent Activity</h3>{closings.slice(0, 5).map((r) => <div key={r.id} className="flex justify-between border-t py-2 text-[10px]"><span>{r.closing_date} · {(r.shift ?? "full_day").replace("_", " ")}</span><span className="capitalize">{r.classification}</span></div>)}</div><div className="rounded-lg border border-[#dce8f2] p-4"><h3 className="mb-4 font-bold text-[#17385d]">Quick Information</h3><div className="space-y-3 text-xs"><div className="flex justify-between"><span>Currency</span><strong>{currency.symbol} ({currency.code})</strong></div><div className="flex justify-between"><span>Report Generated</span><strong>{new Date().toLocaleString()}</strong></div><div className="flex justify-between"><span>Balanced Closings</span><strong>{balanced}</strong></div><div className="flex justify-between"><span>Excess Total</span><strong>{formatCurrencyAmount(excess, currency)}</strong></div></div></div></div>
    <div className="flex flex-wrap justify-end gap-2 border-t p-5 print:hidden"><button onClick={download} className="rounded-md border px-4 py-2 text-xs font-medium">Export Report</button><button onClick={() => window.print()} className="rounded-md bg-[#1478dd] px-4 py-2 text-xs font-semibold text-white">Print Report</button></div>
    <style jsx global>{`@media print { body * { visibility: hidden; } .cash-closing-report, .cash-closing-report * { visibility: visible; } .cash-closing-report { position: absolute; inset: 0; width: 100%; box-shadow: none; border: 0; } }`}</style>
  </section>;
}
