"use client";

import { useMemo, useState } from "react";
import { BarChart3, Calendar, Download, Filter, Lightbulb, Search, ShoppingCart, TrendingUp, Users, Wallet, Boxes } from "lucide-react";
import { formatCurrency } from "@/lib/sales/format";
import type { BranchMetric } from "@/lib/reports/branch-performance";

const colors = ["#16a34a", "#2563eb", "#7c3aed", "#f59e0b", "#0891b2", "#dc2626"];

export function BranchPerformanceView({ rows, currency, from, to }: { rows: BranchMetric[]; currency: string; from: string; to: string }) {
  const [query, setQuery] = useState("");
  const [metric, setMetric] = useState<"sales" | "grossProfit" | "stockValue" | "orders" | "customers">("sales");
  const filtered = useMemo(() => rows.filter((row) => row.name.toLowerCase().includes(query.toLowerCase())), [rows, query]);
  const totals = rows.reduce((acc, row) => ({ sales: acc.sales + row.sales, profit: acc.profit + row.grossProfit, stock: acc.stock + row.stockValue, orders: acc.orders + row.orders, customers: acc.customers + row.customers }), { sales: 0, profit: 0, stock: 0, orders: 0, customers: 0 });
  const best = [...rows].sort((a, b) => b.sales - a.sales)[0];
  const low = [...rows].sort((a, b) => a.sales - b.sales)[0];
  const exportCsv = () => {
    const csv = [["Branch", "Sales", "Gross Profit", "Stock Value", "Orders", "Customers", "Margin"], ...rows.map((r) => [r.name, r.sales, r.grossProfit, r.stockValue, r.orders, r.customers, `${r.margin}%`])].map((r) => r.join(",")).join("\n");
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = `branch-performance-${from}-to-${to}.csv`; link.click(); URL.revokeObjectURL(link.href);
  };
  const cards = [
    ["Total Sales", formatCurrency(totals.sales, currency), TrendingUp, "sales"],
    ["Gross Profit", formatCurrency(totals.profit, currency), Wallet, "profit"],
    ["Total Stock Value", formatCurrency(totals.stock, currency), Boxes, "stock"],
    ["Total Orders", totals.orders.toLocaleString(), ShoppingCart, "orders"],
    ["Total Customers", totals.customers.toLocaleString(), Users, "customers"],
  ] as const;
  const max = Math.max(1, ...rows.map((row) => row[metric]));
  return <main className="mx-auto max-w-[1500px] space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 text-xs text-ledger-400">Home <span className="mx-1">›</span> Reports <span className="mx-1">›</span> Branch Performance</div><h1 className="font-display text-2xl font-bold text-ink-900 dark:text-white">Branch Performance</h1><p className="mt-1 text-sm text-ledger-500">Compare branch performance and track key metrics across your locations.</p></div><div className="flex items-center gap-2"><label className="flex items-center gap-2 rounded-xl border border-ledger-200 bg-white px-3 py-2 text-xs dark:border-ledger-700 dark:bg-ink-900"><Calendar className="h-4 w-4 text-ledger-400" /><input type="date" defaultValue={from} className="bg-transparent" /><span>to</span><input type="date" defaultValue={to} className="bg-transparent" /></label><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-3 py-2 text-xs font-semibold text-white"><Download className="h-4 w-4" /> Export</button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-ledger-100 bg-white p-4 shadow-card dark:border-ledger-700 dark:bg-ink-900"><div className="flex items-center gap-2 text-xs text-ledger-500"><span className="rounded-lg bg-brand-50 p-2 text-brand-600"><Icon className="h-4 w-4" /></span>{label}</div><p className="mt-3 text-xl font-bold text-ink-900 dark:text-white">{value}</p><p className="mt-1 text-[11px] text-signal">↑ across selected period</p></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-5"><section className="rounded-2xl border border-ledger-100 bg-white p-5 shadow-card dark:border-ledger-700 dark:bg-ink-900"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-ink-900 dark:text-white">Branch Performance Overview</h2><p className="text-xs text-ledger-500">Compare branches for the selected period.</p></div><div className="flex gap-1 rounded-lg bg-ledger-50 p-1 dark:bg-ink-950">{(["sales", "grossProfit", "stockValue", "orders", "customers"] as const).map((key) => <button key={key} onClick={() => setMetric(key)} className={`rounded-md px-2 py-1 text-[10px] font-semibold ${metric === key ? "bg-brand-600 text-white" : "text-ledger-500"}`}>{key === "grossProfit" ? "Profit" : key === "stockValue" ? "Stock" : key[0].toUpperCase() + key.slice(1)}</button>)}</div></div><div className="flex h-64 items-end gap-4 overflow-x-auto border-b border-ledger-100 px-2 pt-4 dark:border-ledger-700">{rows.map((row, index) => <div key={row.id} className="flex min-w-20 flex-1 flex-col items-center justify-end gap-2"><span className="text-[10px] font-semibold text-ledger-500">{metric === "orders" || metric === "customers" ? row[metric] : formatCurrency(row[metric], currency)}</span><div className="w-full rounded-t-lg" style={{ height: `${Math.max(8, (row[metric] / max) * 190)}px`, backgroundColor: colors[index % colors.length] }} /><span className="max-w-24 truncate text-center text-[10px] font-medium text-ink-700 dark:text-ledger-300">{row.name}</span></div>)}</div></section>
    <section className="rounded-2xl border border-ledger-100 bg-white shadow-card dark:border-ledger-700 dark:bg-ink-900"><div className="flex flex-wrap items-center gap-3 border-b border-ledger-100 p-4 dark:border-ledger-700"><h2 className="font-semibold text-ink-900 dark:text-white">Branch Performance Details</h2><div className="relative ml-auto"><Search className="absolute left-3 top-2.5 h-4 w-4 text-ledger-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search branches..." className="rounded-xl border border-ledger-200 py-2 pl-9 pr-3 text-xs dark:border-ledger-700 dark:bg-ink-950" /></div><button className="rounded-xl border border-ledger-200 p-2 text-ledger-500"><Filter className="h-4 w-4" /></button></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="bg-ledger-50 uppercase tracking-wide text-ledger-500 dark:bg-ink-950"><tr>{["Branch", "Total Sales", "Gross Profit", "Stock Value", "Orders", "Customers", "Profit Margin"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-ledger-100 dark:divide-ledger-700">{filtered.map((row, index) => <tr key={row.id}><td className="px-4 py-4"><div className="font-semibold text-ink-900 dark:text-white">{row.name}</div><div className="text-[11px] text-ledger-400">{row.city ?? "—"}</div></td><td className="px-4 py-4 font-semibold">{formatCurrency(row.sales, currency)}<div className="text-[10px] text-signal">↑ {row.change}%</div></td><td className="px-4 py-4">{formatCurrency(row.grossProfit, currency)}</td><td className="px-4 py-4">{formatCurrency(row.stockValue, currency)}</td><td className="px-4 py-4">{row.orders}</td><td className="px-4 py-4">{row.customers}</td><td className="px-4 py-4">{row.margin}%</td></tr>)}</tbody></table></div></section></div>
    <aside className="space-y-4"><div className="rounded-2xl border border-ledger-100 bg-white p-5 shadow-card dark:border-ledger-700 dark:bg-ink-900"><h3 className="font-semibold">Quick Actions</h3><div className="mt-3 space-y-2"><button onClick={exportCsv} className="flex w-full items-center gap-2 rounded-xl border border-ledger-200 px-3 py-2 text-left text-xs font-semibold"><Download className="h-4 w-4" /> Export Report</button><a href="/reports" className="flex items-center gap-2 rounded-xl border border-ledger-200 px-3 py-2 text-xs font-semibold"><BarChart3 className="h-4 w-4" /> View Reports</a></div></div>{best && <div className="rounded-2xl bg-emerald-50 p-5 text-sm"><div className="flex items-center gap-2 font-semibold text-emerald-800"><Lightbulb className="h-4 w-4" /> Insight</div><p className="mt-3 text-xs text-emerald-700"><strong>{best.name}</strong> leads sales for this period at {formatCurrency(best.sales, currency)}.</p></div>}<div className="rounded-2xl border border-ledger-100 bg-white p-5 shadow-card dark:border-ledger-700 dark:bg-ink-900"><p className="text-xs font-semibold uppercase text-ledger-400">Top Performing Branch</p><p className="mt-3 font-semibold">{best?.name ?? "No data"}</p><p className="mt-1 text-sm text-signal">{best ? formatCurrency(best.sales, currency) : "—"}</p></div><div className="rounded-2xl border border-ledger-100 bg-white p-5 shadow-card dark:border-ledger-700 dark:bg-ink-900"><p className="text-xs font-semibold uppercase text-ledger-400">Lowest Performing Branch</p><p className="mt-3 font-semibold">{low?.name ?? "No data"}</p><p className="mt-1 text-sm text-alert">{low ? formatCurrency(low.sales, currency) : "—"}</p></div></aside></div>
  </main>;
}
