"use client";

import { useMemo, useState } from "react";
import { Download, Pause, Play, Plus, RefreshCw } from "lucide-react";
import { adjustCommunicationCredits, setCommunicationProviderEnabled, setOrganizationMessagingSuspended, updateCommunicationCampaignStatus } from "./actions";
import { formatMoney } from "@/lib/currency";

type Organization = { id: string; organization_id: string; name: string; plan_id: string | null; status: string; updated_at: string };
type Usage = { organization_id: string; monthly_activity: number | null; sales_volume: number | null; updated_at: string };
type Billing = { organization_id: string; amount: number; status: string; issued_at: string };
type Log = { id: string; organization_id: string | null; action: string; module: string; metadata: Record<string, unknown> | null; created_at: string };
type CreditAccount = { organization_id: string; credit_balance: number; sms_credits: number; whatsapp_credits: number; email_credits: number; messaging_suspended: boolean };
type CreditTransaction = { id: string; organization_id: string; amount: number; transaction_type: string; note: string | null; created_at: string };
type Campaign = { id: string; organization_id: string; name: string; campaign_type: string; audience: string; messages_sent: number; delivered: number; read_count: number; click_rate: number; status: string };
type Provider = { provider_name: string; channel: "SMS" | "WhatsApp" | "Email"; enabled: boolean; status: string };
type Alert = { id: string; title: string; severity: string; detail: string };
type Tab = "Overview" | "Organizations" | "SMS Management" | "WhatsApp Management" | "Email Management" | "Communication Credits" | "Campaign Monitoring" | "Usage Analytics" | "Billing & Revenue" | "Communication Logs" | "Provider Settings" | "System Alerts";

const tabs: Tab[] = ["Overview", "Organizations", "SMS Management", "WhatsApp Management", "Email Management", "Communication Credits", "Campaign Monitoring", "Usage Analytics", "Billing & Revenue", "Communication Logs", "Provider Settings", "System Alerts"];
const providerGroups: Array<[string, "SMS" | "WhatsApp" | "Email", string[]]> = [
  ["SMS Providers", "SMS", ["Twilio", "Hubtel", "Arkesel", "Africa's Talking"]],
  ["WhatsApp Providers", "WhatsApp", ["Meta Cloud API", "Twilio WhatsApp"]],
  ["Email Providers", "Email", ["SendGrid", "Resend", "Mailgun", "SMTP"]],
];

function Card({ children }: { children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">{children}</section>; }
function Table({ headers, children }: { headers: string[]; children: React.ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead><tr className="border-b text-[10px] uppercase tracking-wider text-slate-400">{headers.map((header) => <th className="p-3" key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>; }

export default function CommunicationManagementWorkspace({ organizations, usage, billing, logs, creditAccounts, creditTransactions, campaigns: initialCampaigns, providers, alerts }: { organizations: Organization[]; usage: Usage[]; billing: Billing[]; logs: Log[]; creditAccounts: CreditAccount[]; creditTransactions: CreditTransaction[]; campaigns: Campaign[]; providers: Provider[]; alerts: Alert[] }) {
  const [tab, setTab] = useState<Tab>("Overview");
  const [query, setQuery] = useState("");
  const [campaigns, setCampaigns] = useState(initialCampaigns);
  const [providerState, setProviderState] = useState<Record<string, boolean>>(() => Object.fromEntries(providers.map((provider) => [provider.provider_name, provider.enabled])));
  const [suspended, setSuspended] = useState<Record<string, boolean>>(() => Object.fromEntries(creditAccounts.map((account) => [account.organization_id, account.messaging_suspended])));
  const totalMessages = usage.reduce((sum, row) => sum + Number(row.monthly_activity ?? 0), 0);
  const totalRevenue = billing.filter((row) => row.status === "paid").reduce((sum, row) => sum + Number(row.amount ?? 0), 0);
  const filteredOrganizations = useMemo(() => organizations.filter((organization) => organization.name.toLowerCase().includes(query.toLowerCase())), [organizations, query]);
  const balance = (organizationId: string) => Number(creditAccounts.find((account) => account.organization_id === organizationId)?.credit_balance ?? 0);
  const orgName = (organizationId: string | null) => organizations.find((organization) => organization.organization_id === organizationId)?.name ?? "Platform";
  const updateSuspension = async (organizationId: string) => { const next = !suspended[organizationId]; await setOrganizationMessagingSuspended(organizationId, next); setSuspended((current) => ({ ...current, [organizationId]: next })); };
  const updateCredits = async (organizationId: string, amount: number) => { await adjustCommunicationCredits(organizationId, amount, amount > 0 ? "Platform top-up" : "Platform deduction"); };
  const updateCampaign = async (campaign: Campaign) => { const status = campaign.status.toLowerCase() === "running" ? "paused" : "running"; await updateCommunicationCampaignStatus(campaign.id, status); setCampaigns((current) => current.map((item) => item.id === campaign.id ? { ...item, status } : item)); };
  const updateProvider = async (provider: Provider, channel: Provider["channel"]) => { const enabled = !providerState[provider.provider_name]; await setCommunicationProviderEnabled(provider.provider_name, channel, enabled); setProviderState((current) => ({ ...current, [provider.provider_name]: enabled })); };
  const exportCsv = (rows: string[][], name: string) => { const content = rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([content], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); };

  return <main className="mx-auto max-w-[1600px] space-y-5 p-6">
    <div><p className="text-xs font-semibold uppercase tracking-widest text-blue-600">Enterprise communication center</p><h2 className="mt-1 text-2xl font-bold text-slate-950">Manage every organization’s messaging</h2><p className="text-sm text-slate-500">Persistent platform controls for channels, credits, campaigns, providers, billing and alerts.</p></div>
    <div className="flex gap-1 overflow-x-auto rounded-xl border bg-white p-1">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold ${tab === item ? "bg-blue-600 text-white" : "text-slate-500 hover:bg-slate-50"}`}>{item}</button>)}</div>
    {tab === "Overview" && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Organizations", organizations.length], ["Messages", totalMessages.toLocaleString()], ["Revenue", formatMoney(totalRevenue)], ["Active Campaigns", campaigns.filter((campaign) => ["running", "scheduled"].includes(campaign.status.toLowerCase())).length], ["Failed Logs", logs.filter((log) => /fail/i.test(log.action)).length], ["Active Providers", providers.filter((provider) => provider.enabled).length], ["Open Alerts", alerts.length], ["Credit Accounts", creditAccounts.length]].map(([label, value]) => <Card key={String(label)}><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></Card>)}</div>}
    {tab === "Organizations" && <Card><div className="mb-4 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search organizations" className="h-9 flex-1 rounded-lg border px-3 text-xs" /><button onClick={() => exportCsv([["Organization", "Balance", "Status"], ...filteredOrganizations.map((organization) => [organization.name, formatMoney(balance(organization.organization_id)), suspended[organization.organization_id] ? "Suspended" : "Active"])], "communication-organizations.csv")} className="rounded-lg border px-3 text-xs"><Download className="mr-1 inline h-3.5 w-3.5" />Export</button></div><Table headers={["Organization", "Plan", "Balance", "Usage", "Status", "Actions"]}>{filteredOrganizations.map((organization) => <tr className="border-b" key={organization.id}><td className="p-3 font-semibold">{organization.name}</td><td className="p-3">{organization.plan_id ?? "Default"}</td><td className="p-3">{formatMoney(balance(organization.organization_id))}</td><td className="p-3">{usage.find((row) => row.organization_id === organization.organization_id)?.monthly_activity ?? 0}</td><td className="p-3">{suspended[organization.organization_id] ? "Suspended" : "Active"}</td><td className="p-3"><button onClick={() => void updateSuspension(organization.organization_id)} className="rounded border px-2 py-1">{suspended[organization.organization_id] ? "Reactivate" : "Suspend"}</button></td></tr>)}</Table></Card>}
    {tab === "Communication Credits" && <Card><Table headers={["Organization", "Balance", "SMS", "WhatsApp", "Email", "Actions"]}>{organizations.map((organization) => { const account = creditAccounts.find((item) => item.organization_id === organization.organization_id); return <tr className="border-b" key={organization.id}><td className="p-3 font-semibold">{organization.name}</td><td className="p-3">{formatMoney(balance(organization.organization_id))}</td><td className="p-3">{account?.sms_credits ?? 0}</td><td className="p-3">{account?.whatsapp_credits ?? 0}</td><td className="p-3">{account?.email_credits ?? 0}</td><td className="flex gap-2 p-3"><button onClick={() => void updateCredits(organization.organization_id, 500)} className="rounded bg-blue-600 px-2 py-1 text-white">Top Up</button><button onClick={() => void updateCredits(organization.organization_id, -100)} className="rounded border px-2 py-1">Deduct</button></td></tr>; })}</Table><h3 className="mt-6 font-semibold">Transaction History</h3><Table headers={["Date", "Organization", "Type", "Amount", "Note"]}>{creditTransactions.map((transaction) => <tr className="border-b" key={transaction.id}><td className="p-3">{new Date(transaction.created_at).toLocaleString()}</td><td className="p-3">{orgName(transaction.organization_id)}</td><td className="p-3">{transaction.transaction_type}</td><td className="p-3">{formatMoney(transaction.amount)}</td><td className="p-3">{transaction.note ?? "—"}</td></tr>)}</Table></Card>}
    {(tab === "SMS Management" || tab === "WhatsApp Management" || tab === "Email Management") && <Card><Table headers={["Organization", "Channel", "Messages", "Usage", "Status"]}>{organizations.map((organization) => <tr className="border-b" key={organization.id}><td className="p-3 font-semibold">{organization.name}</td><td className="p-3">{tab.replace(" Management", "")}</td><td className="p-3">{usage.find((row) => row.organization_id === organization.organization_id)?.monthly_activity ?? 0}</td><td className="p-3">{formatMoney(balance(organization.organization_id))}</td><td className="p-3">{suspended[organization.organization_id] ? "Suspended" : "Active"}</td></tr>)}</Table></Card>}
    {tab === "Campaign Monitoring" && <Card><Table headers={["Campaign", "Organization", "Type", "Audience", "Sent", "Delivered", "Read", "Status", "Action"]}>{campaigns.map((campaign) => <tr className="border-b" key={campaign.id}><td className="p-3 font-semibold">{campaign.name}</td><td className="p-3">{orgName(campaign.organization_id)}</td><td className="p-3">{campaign.campaign_type}</td><td className="p-3">{campaign.audience}</td><td className="p-3">{campaign.messages_sent}</td><td className="p-3">{campaign.delivered}</td><td className="p-3">{campaign.read_count}</td><td className="p-3">{campaign.status}</td><td className="p-3"><button onClick={() => void updateCampaign(campaign)}>{campaign.status.toLowerCase() === "running" ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}</button></td></tr>)}</Table></Card>}
    {tab === "Communication Logs" && <Card><div className="mb-4 flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search logs" className="h-9 flex-1 rounded-lg border px-3 text-xs" /><RefreshCw className="m-2 h-4 w-4 text-slate-400" /></div><Table headers={["Date", "Organization", "Channel", "Action", "Status"]}>{logs.filter((log) => !query || log.action.toLowerCase().includes(query.toLowerCase())).map((log) => <tr className="border-b" key={log.id}><td className="p-3">{new Date(log.created_at).toLocaleString()}</td><td className="p-3">{orgName(log.organization_id)}</td><td className="p-3">{String(log.metadata?.channel ?? "—")}</td><td className="p-3">{log.action}</td><td className="p-3">{String(log.metadata?.status ?? "Recorded")}</td></tr>)}</Table></Card>}
    {tab === "Provider Settings" && <div className="grid gap-4 md:grid-cols-3">{providerGroups.map(([group, channel, names]) => <Card key={group}><h3 className="font-semibold">{group}</h3>{names.map((name) => { const provider = providers.find((item) => item.provider_name === name) ?? { provider_name: name, channel, enabled: false, status: "not_configured" as const }; return <div className="mt-3 flex items-center justify-between rounded-lg bg-slate-50 p-3 text-xs" key={name}><span>{name}</span><button onClick={() => void updateProvider(provider, channel)} className="rounded-full border px-2 py-1">{providerState[name] ? "Enabled" : "Disabled"}</button></div>; })}</Card>)}</div>}
    {tab === "System Alerts" && <Card><Table headers={["Severity", "Title", "Detail"]}>{alerts.map((alert) => <tr className="border-b" key={alert.id}><td className="p-3">{alert.severity}</td><td className="p-3 font-semibold">{alert.title}</td><td className="p-3">{alert.detail}</td></tr>)}</Table></Card>}
    {(tab === "Usage Analytics" || tab === "Billing & Revenue") && <Card><h3 className="font-semibold">{tab}</h3><p className="mt-2 text-sm text-slate-500">Aggregated from persisted platform records.</p><Table headers={["Organization", "Usage", "Revenue"]}>{organizations.map((organization) => <tr className="border-b" key={organization.id}><td className="p-3 font-semibold">{organization.name}</td><td className="p-3">{usage.find((row) => row.organization_id === organization.organization_id)?.monthly_activity ?? 0}</td><td className="p-3">{formatMoney(billing.filter((row) => row.organization_id === organization.organization_id).reduce((sum, row) => sum + Number(row.amount ?? 0), 0))}</td></tr>)}</Table></Card>}
    {(tab === "Email Management" || tab === "WhatsApp Management" || tab === "SMS Management") && null}
  </main>;
}
