import type {
  RoleDefinition,
  ModulePermissionConfig,
  ModuleCategory,
  PermissionAction,
  ManagedUser,
  UserBranch,
  AuditLogEntry
} from "./types";

export const PERMISSION_ACTIONS: { key: PermissionAction; label: string; description: string }[] = [
  { key: "view", label: "View", description: "Can view records and lists" },
  { key: "create", label: "Create", description: "Can create new records" },
  { key: "edit", label: "Edit", description: "Can modify existing records" },
  { key: "delete", label: "Delete", description: "Can remove or archive records" },
  { key: "approve", label: "Approve", description: "Can authorize transactions, transfers, & budgets" },
  { key: "export", label: "Export", description: "Can export datasets to CSV / Excel / PDF" },
  { key: "print", label: "Print", description: "Can print receipts, invoices, and audit slips" }
];

export const MODULE_CONFIGS: ModulePermissionConfig[] = [
  { key: "dashboard", name: "Dashboard", description: "Overview metrics, KPIs, and executive charts", iconName: "LayoutDashboard", supportedActions: ["view", "export", "print"] },
  { key: "sales", name: "Sales", description: "Quotations, invoices, sales orders, and returns", iconName: "Receipt", supportedActions: ["view", "create", "edit", "delete", "approve", "export", "print"] },
  { key: "pos", name: "POS", description: "Point of sale register, cashier terminal, and till cashups", iconName: "ShoppingCart", supportedActions: ["view", "create", "edit", "delete", "export", "print"] },
  { key: "products", name: "Products", description: "Product catalog, pricing tiers, barcodes, and units", iconName: "Boxes", supportedActions: ["view", "create", "edit", "delete", "approve", "export", "print"] },
  { key: "inventory", name: "Inventory", description: "Stock levels, batches, stock takes, and adjustments", iconName: "Layers", supportedActions: ["view", "create", "edit", "delete", "approve", "export", "print"] },
  { key: "transfers", name: "Transfers", description: "Inter-branch and warehouse stock transfers", iconName: "Truck", supportedActions: ["view", "create", "edit", "delete", "approve", "export", "print"] },
  { key: "purchases", name: "Purchases", description: "Purchase orders, goods receipts, and vendor bills", iconName: "ShoppingBag", supportedActions: ["view", "create", "edit", "delete", "approve", "export", "print"] },
  { key: "expenses", name: "Expenses", description: "Operating expenses, receipts, and petty cash", iconName: "Tag", supportedActions: ["view", "create", "edit", "delete", "approve", "export", "print"] },
  { key: "customers", name: "Customers", description: "Customer accounts, credit limits, and loyalty", iconName: "Contact", supportedActions: ["view", "create", "edit", "delete", "export", "print"] },
  { key: "suppliers", name: "Suppliers", description: "Vendor contacts, price agreements, and lead times", iconName: "Truck", supportedActions: ["view", "create", "edit", "delete", "export", "print"] },
  { key: "accounting", name: "Accounting", description: "General ledger, chart of accounts, and journals", iconName: "Wallet", supportedActions: ["view", "create", "edit", "delete", "approve", "export", "print"] },
  { key: "hrm_payroll", name: "HRM & Payroll", description: "Employee records, attendance, leaves, and payslips", iconName: "Users", supportedActions: ["view", "create", "edit", "delete", "approve", "export", "print"] },
  { key: "reports", name: "Reports", description: "Financial, sales, inventory, and tax reports", iconName: "BarChart3", supportedActions: ["view", "export", "print"] },
  { key: "user_management", name: "User Management", description: "User accounts, roles, access matrix, and audit logs", iconName: "ShieldCheck", supportedActions: ["view", "create", "edit", "delete", "approve", "export", "print"] },
  { key: "settings", name: "Settings", description: "System configuration, currencies, taxes, and integrations", iconName: "Settings", supportedActions: ["view", "create", "edit", "delete", "export", "print"] }
];

export const DEPARTMENTS = [
  "Sales & Marketing",
  "Inventory & Warehouse",
  "Finance & Accounts",
  "Human Resources",
  "Operations & Logistics",
  "Executive Management",
  "Information Technology",
  "Customer Support"
];

export const DEFAULT_BRANCHES: UserBranch[] = [
  { id: "b-head", name: "Head Office", code: "ACC-HO", isMain: true },
  { id: "b-accra", name: "Accra Main Branch", code: "ACC-01" },
  { id: "b-kumasi", name: "Kumasi Branch", code: "KSI-01" },
  { id: "b-takoradi", name: "Takoradi Branch", code: "TKD-01" },
  { id: "b-tema", name: "Tema Branch", code: "TMA-01" },
  { id: "b-ho", name: "Ho Branch", code: "HO-01" },
  { id: "b-cape", name: "Cape Coast Branch", code: "CC-01" },
  { id: "b-sunyani", name: "Sunyani Branch", code: "SNY-01" },
  { id: "b-tamale", name: "Tamale Branch", code: "TML-01" },
  { id: "b-wa", name: "Wa Branch", code: "WA-01" }
];

const ALL_ACTIONS: PermissionAction[] = ["view", "create", "edit", "delete", "approve", "export", "print"];

export const DEFAULT_ROLES: RoleDefinition[] = [
  {
    id: "role-admin",
    key: "administrator",
    name: "Administrator",
    description: "Full unrestricted access across all business modules, settings, and branches.",
    userCount: 4,
    permissionCount: 58,
    isSystem: true,
    scope: "all_branches",
    badgeColor: "bg-purple-100 text-purple-700 border-purple-200 dark:bg-purple-950/60 dark:text-purple-300 dark:border-purple-800",
    permissions: MODULE_CONFIGS.reduce((acc, m) => {
      acc[m.key] = [...m.supportedActions];
      return acc;
    }, {} as Record<ModuleCategory, PermissionAction[]>),
    approvalCapabilities: {
      stockTransfers: true,
      purchases: true,
      expenses: true,
      priceUpdates: true,
      stockAdjustments: true
    }
  },
  {
    id: "role-manager",
    key: "manager",
    name: "Manager",
    description: "Manages branch operations, daily sales, approvals, stock adjustments, and staff.",
    userCount: 5,
    permissionCount: 46,
    isSystem: true,
    scope: "branch_specific",
    badgeColor: "bg-blue-100 text-blue-700 border-blue-200 dark:bg-blue-950/60 dark:text-blue-300 dark:border-blue-800",
    permissions: {
      dashboard: ["view", "export", "print"],
      sales: ["view", "create", "edit", "approve", "export", "print"],
      pos: ["view", "create", "edit", "export", "print"],
      products: ["view", "create", "edit", "export", "print"],
      inventory: ["view", "create", "edit", "approve", "export", "print"],
      transfers: ["view", "create", "edit", "approve", "export", "print"],
      purchases: ["view", "create", "edit", "approve", "export", "print"],
      expenses: ["view", "create", "edit", "approve", "export", "print"],
      customers: ["view", "create", "edit", "export", "print"],
      suppliers: ["view", "create", "edit", "export", "print"],
      accounting: ["view", "export"],
      hrm_payroll: ["view", "create", "edit", "export", "print"],
      reports: ["view", "export", "print"],
      user_management: ["view"],
      settings: ["view"]
    },
    approvalCapabilities: {
      stockTransfers: true,
      purchases: true,
      expenses: true,
      priceUpdates: false,
      stockAdjustments: true
    }
  },
  {
    id: "role-sales",
    key: "sales_officer",
    name: "Sales Associate",
    description: "Generates quotes, orders, customer records, and handles customer engagement.",
    userCount: 6,
    permissionCount: 22,
    isSystem: true,
    scope: "branch_specific",
    badgeColor: "bg-emerald-100 text-emerald-700 border-emerald-200 dark:bg-emerald-950/60 dark:text-emerald-300 dark:border-emerald-800",
    permissions: {
      dashboard: ["view"],
      sales: ["view", "create", "edit", "export", "print"],
      pos: ["view", "create", "print"],
      products: ["view", "export"],
      inventory: ["view"],
      transfers: ["view"],
      purchases: [],
      expenses: ["create"],
      customers: ["view", "create", "edit", "export", "print"],
      suppliers: ["view"],
      accounting: [],
      hrm_payroll: [],
      reports: ["view"],
      user_management: [],
      settings: []
    },
    approvalCapabilities: {
      stockTransfers: false,
      purchases: false,
      expenses: false,
      priceUpdates: false,
      stockAdjustments: false
    }
  },
  {
    id: "role-cashier",
    key: "cashier",
    name: "Cashier",
    description: "Operates POS terminals, issues receipts, takes payments, and manages register.",
    userCount: 4,
    permissionCount: 14,
    isSystem: true,
    scope: "branch_specific",
    badgeColor: "bg-amber-100 text-amber-700 border-amber-200 dark:bg-amber-950/60 dark:text-amber-300 dark:border-amber-800",
    permissions: {
      dashboard: ["view"],
      sales: ["view", "create", "print"],
      pos: ["view", "create", "edit", "print"],
      products: ["view"],
      inventory: ["view"],
      transfers: [],
      purchases: [],
      expenses: ["create"],
      customers: ["view", "create"],
      suppliers: [],
      accounting: [],
      hrm_payroll: [],
      reports: [],
      user_management: [],
      settings: []
    },
    approvalCapabilities: {
      stockTransfers: false,
      purchases: false,
      expenses: false,
      priceUpdates: false,
      stockAdjustments: false
    }
  },
  {
    id: "role-inventory",
    key: "inventory_officer",
    name: "Inventory Clerk",
    description: "Oversees stock receiving, stock counts, adjustments, and warehouse transfers.",
    userCount: 3,
    permissionCount: 28,
    isSystem: true,
    scope: "branch_specific",
    badgeColor: "bg-cyan-100 text-cyan-700 border-cyan-200 dark:bg-cyan-950/60 dark:text-cyan-300 dark:border-cyan-800",
    permissions: {
      dashboard: ["view"],
      sales: ["view"],
      pos: [],
      products: ["view", "create", "edit", "export", "print"],
      inventory: ["view", "create", "edit", "export", "print"],
      transfers: ["view", "create", "edit", "export", "print"],
      purchases: ["view", "create", "edit", "export", "print"],
      expenses: [],
      customers: [],
      suppliers: ["view", "create", "edit", "export"],
      accounting: [],
      hrm_payroll: [],
      reports: ["view", "export"],
      user_management: [],
      settings: []
    },
    approvalCapabilities: {
      stockTransfers: false,
      purchases: false,
      expenses: false,
      priceUpdates: false,
      stockAdjustments: false
    }
  },
  {
    id: "role-hr",
    key: "hr_officer",
    name: "HR Officer",
    description: "Manages employee records, shifts, attendance, leaves, and payroll runs.",
    userCount: 1,
    permissionCount: 20,
    isSystem: true,
    scope: "all_branches",
    badgeColor: "bg-indigo-100 text-indigo-700 border-indigo-200 dark:bg-indigo-950/60 dark:text-indigo-300 dark:border-indigo-800",
    permissions: {
      dashboard: ["view"],
      sales: [],
      pos: [],
      products: [],
      inventory: [],
      transfers: [],
      purchases: [],
      expenses: ["view", "create"],
      customers: [],
      suppliers: [],
      accounting: ["view"],
      hrm_payroll: ["view", "create", "edit", "delete", "approve", "export", "print"],
      reports: ["view", "export", "print"],
      user_management: ["view"],
      settings: []
    },
    approvalCapabilities: {
      stockTransfers: false,
      purchases: false,
      expenses: false,
      priceUpdates: false,
      stockAdjustments: false
    }
  },
  {
    id: "role-accountant",
    key: "accountant",
    name: "Accountant",
    description: "Financial reconciliations, expenses audits, journal entries, and tax returns.",
    userCount: 1,
    permissionCount: 32,
    isSystem: true,
    scope: "all_branches",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200 dark:bg-teal-950/60 dark:text-teal-300 dark:border-teal-800",
    permissions: {
      dashboard: ["view", "export", "print"],
      sales: ["view", "export", "print"],
      pos: ["view", "export"],
      products: ["view", "export"],
      inventory: ["view", "export"],
      transfers: ["view", "export"],
      purchases: ["view", "approve", "export", "print"],
      expenses: ["view", "create", "edit", "approve", "export", "print"],
      customers: ["view", "export"],
      suppliers: ["view", "export"],
      accounting: ["view", "create", "edit", "approve", "export", "print"],
      hrm_payroll: ["view", "export"],
      reports: ["view", "export", "print"],
      user_management: ["view"],
      settings: ["view"]
    },
    approvalCapabilities: {
      stockTransfers: false,
      purchases: true,
      expenses: true,
      priceUpdates: false,
      stockAdjustments: false
    }
  }
];

export const INITIAL_USERS: ManagedUser[] = [
  {
    id: "usr-01",
    userId: "u-01",
    name: "John Doe",
    fullName: "John Doe",
    email: "john.doe@thinksales.com",
    phone: "+233 24 412 3456",
    employeeId: "TS-EMP-001",
    avatarUrl: null,
    role: "administrator",
    roleLabel: "Administrator",
    status: "active",
    department: "Executive Management",
    locationId: "b-head",
    locationName: "Head Office",
    secondaryBranches: ["b-accra", "b-kumasi", "b-tema"],
    secondaryBranchNames: ["Accra Main Branch", "Kumasi Branch", "Tema Branch"],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    joinedAt: "2024-01-15T08:00:00Z",
    isSelf: true,
    twoFactorEnabled: true,
    branchScope: "all",
    approvalPermissions: { stockTransfers: true, purchases: true, expenses: true, priceUpdates: true, stockAdjustments: true, maxExpenseAmount: 500000, maxPurchaseAmount: 1000000 }
  },
  {
    id: "usr-02",
    userId: "u-02",
    name: "Mary Addo",
    fullName: "Mary Addo",
    email: "mary.addo@thinksales.com",
    phone: "+233 20 876 5432",
    employeeId: "TS-EMP-002",
    avatarUrl: null,
    role: "manager",
    roleLabel: "Manager",
    status: "active",
    department: "Operations & Logistics",
    locationId: "b-kumasi",
    locationName: "Kumasi Branch",
    secondaryBranches: ["b-sunyani"],
    secondaryBranchNames: ["Sunyani Branch"],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    joinedAt: "2024-02-01T09:30:00Z",
    isSelf: false,
    twoFactorEnabled: true,
    branchScope: "assigned",
    approvalPermissions: { stockTransfers: true, purchases: true, expenses: true, priceUpdates: false, stockAdjustments: true, maxExpenseAmount: 25000, maxPurchaseAmount: 50000 }
  },
  {
    id: "usr-03",
    userId: "u-03",
    name: "Daniel K.",
    fullName: "Daniel Koomson",
    email: "daniel.k@thinksales.com",
    phone: "+233 55 345 6789",
    employeeId: "TS-EMP-003",
    avatarUrl: null,
    role: "sales_officer",
    roleLabel: "Sales Associate",
    status: "active",
    department: "Sales & Marketing",
    locationId: "b-takoradi",
    locationName: "Takoradi Branch",
    secondaryBranches: [],
    secondaryBranchNames: [],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    joinedAt: "2024-03-10T11:15:00Z",
    isSelf: false,
    twoFactorEnabled: false,
    branchScope: "single",
    approvalPermissions: { stockTransfers: false, purchases: false, expenses: false, priceUpdates: false, stockAdjustments: false }
  },
  {
    id: "usr-04",
    userId: "u-04",
    name: "Grace Mensah",
    fullName: "Grace Mensah",
    email: "grace.m@thinksales.com",
    phone: "+233 24 998 8776",
    employeeId: "TS-EMP-004",
    avatarUrl: null,
    role: "cashier",
    roleLabel: "Cashier",
    status: "active",
    department: "Sales & Marketing",
    locationId: "b-accra",
    locationName: "Accra Main Branch",
    secondaryBranches: [],
    secondaryBranchNames: [],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    joinedAt: "2024-03-15T14:20:00Z",
    isSelf: false,
    twoFactorEnabled: true,
    branchScope: "single",
    approvalPermissions: { stockTransfers: false, purchases: false, expenses: false, priceUpdates: false, stockAdjustments: false }
  },
  {
    id: "usr-05",
    userId: "u-05",
    name: "James Mensah",
    fullName: "James Mensah",
    email: "james.m@thinksales.com",
    phone: "+233 50 112 2334",
    employeeId: "TS-EMP-005",
    avatarUrl: null,
    role: "inventory_officer",
    roleLabel: "Inventory Clerk",
    status: "inactive",
    department: "Inventory & Warehouse",
    locationId: "b-tema",
    locationName: "Tema Branch",
    secondaryBranches: ["b-accra"],
    secondaryBranchNames: ["Accra Main Branch"],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    joinedAt: "2024-04-01T10:00:00Z",
    isSelf: false,
    twoFactorEnabled: false,
    branchScope: "assigned",
    approvalPermissions: { stockTransfers: false, purchases: false, expenses: false, priceUpdates: false, stockAdjustments: false }
  },
  {
    id: "usr-06",
    userId: "u-06",
    name: "Akosua Gyamfi",
    fullName: "Akosua Gyamfi",
    email: "akosua.g@thinksales.com",
    phone: "+233 27 554 4332",
    employeeId: "TS-EMP-006",
    avatarUrl: null,
    role: "sales_officer",
    roleLabel: "Sales Associate",
    status: "active",
    department: "Sales & Marketing",
    locationId: "b-ho",
    locationName: "Ho Branch",
    secondaryBranches: [],
    secondaryBranchNames: [],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    joinedAt: "2024-04-12T09:05:00Z",
    isSelf: false,
    twoFactorEnabled: true,
    branchScope: "single",
    approvalPermissions: { stockTransfers: false, purchases: false, expenses: false, priceUpdates: false, stockAdjustments: false }
  },
  {
    id: "usr-07",
    userId: "u-07",
    name: "Michael Ofori",
    fullName: "Michael Ofori",
    email: "michael.o@thinksales.com",
    phone: "+233 24 667 7889",
    employeeId: "TS-EMP-007",
    avatarUrl: null,
    role: "manager",
    roleLabel: "Manager",
    status: "active",
    department: "Operations & Logistics",
    locationId: "b-cape",
    locationName: "Cape Coast Branch",
    secondaryBranches: ["b-takoradi"],
    secondaryBranchNames: ["Takoradi Branch"],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    joinedAt: "2024-04-20T16:45:00Z",
    isSelf: false,
    twoFactorEnabled: true,
    branchScope: "assigned",
    approvalPermissions: { stockTransfers: true, purchases: true, expenses: true, priceUpdates: false, stockAdjustments: true, maxExpenseAmount: 20000, maxPurchaseAmount: 40000 }
  },
  {
    id: "usr-08",
    userId: "u-08",
    name: "Abena Boateng",
    fullName: "Abena Boateng",
    email: "abena.b@thinksales.com",
    phone: "+233 54 887 7665",
    employeeId: "TS-EMP-008",
    avatarUrl: null,
    role: "cashier",
    roleLabel: "Cashier",
    status: "inactive",
    department: "Sales & Marketing",
    locationId: "b-sunyani",
    locationName: "Sunyani Branch",
    secondaryBranches: [],
    secondaryBranchNames: [],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    joinedAt: "2024-05-02T13:30:00Z",
    isSelf: false,
    twoFactorEnabled: false,
    branchScope: "single",
    approvalPermissions: { stockTransfers: false, purchases: false, expenses: false, priceUpdates: false, stockAdjustments: false }
  },
  {
    id: "usr-09",
    userId: "u-09",
    name: "Richard Darko",
    fullName: "Richard Darko",
    email: "richard.d@thinksales.com",
    phone: "+233 20 334 4556",
    employeeId: "TS-EMP-009",
    avatarUrl: null,
    role: "inventory_officer",
    roleLabel: "Inventory Clerk",
    status: "active",
    department: "Inventory & Warehouse",
    locationId: "b-tamale",
    locationName: "Tamale Branch",
    secondaryBranches: ["b-wa"],
    secondaryBranchNames: ["Wa Branch"],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    joinedAt: "2024-05-10T10:15:00Z",
    isSelf: false,
    twoFactorEnabled: true,
    branchScope: "assigned",
    approvalPermissions: { stockTransfers: false, purchases: false, expenses: false, priceUpdates: false, stockAdjustments: false }
  },
  {
    id: "usr-10",
    userId: "u-10",
    name: "Esi Ampofo",
    fullName: "Esi Ampofo",
    email: "esi.a@thinksales.com",
    phone: "+233 55 990 0112",
    employeeId: "TS-EMP-010",
    avatarUrl: null,
    role: "sales_officer",
    roleLabel: "Sales Associate",
    status: "active",
    department: "Sales & Marketing",
    locationId: "b-wa",
    locationName: "Wa Branch",
    secondaryBranches: [],
    secondaryBranchNames: [],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    joinedAt: "2024-05-18T10:10:00Z",
    isSelf: false,
    twoFactorEnabled: true,
    branchScope: "single",
    approvalPermissions: { stockTransfers: false, purchases: false, expenses: false, priceUpdates: false, stockAdjustments: false }
  },
  {
    id: "usr-11",
    userId: "u-11",
    name: "Kwame Nkrumah Jr",
    fullName: "Kwame Nkrumah",
    email: "kwame.n@thinksales.com",
    phone: "+233 24 111 2233",
    employeeId: "TS-EMP-011",
    avatarUrl: null,
    role: "accountant",
    roleLabel: "Accountant",
    status: "active",
    department: "Finance & Accounts",
    locationId: "b-head",
    locationName: "Head Office",
    secondaryBranches: ["b-accra", "b-tema"],
    secondaryBranchNames: ["Accra Main Branch", "Tema Branch"],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    joinedAt: "2024-01-20T08:30:00Z",
    isSelf: false,
    twoFactorEnabled: true,
    branchScope: "all",
    approvalPermissions: { stockTransfers: false, purchases: true, expenses: true, priceUpdates: false, stockAdjustments: false, maxExpenseAmount: 100000, maxPurchaseAmount: 200000 }
  },
  {
    id: "usr-12",
    userId: "u-12",
    name: "Ama Serwaa",
    fullName: "Ama Serwaa",
    email: "ama.s@thinksales.com",
    phone: "+233 50 444 5566",
    employeeId: "TS-EMP-012",
    avatarUrl: null,
    role: "hr_officer",
    roleLabel: "HR Officer",
    status: "active",
    department: "Human Resources",
    locationId: "b-head",
    locationName: "Head Office",
    secondaryBranches: [],
    secondaryBranchNames: [],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    joinedAt: "2024-02-15T09:00:00Z",
    isSelf: false,
    twoFactorEnabled: true,
    branchScope: "all",
    approvalPermissions: { stockTransfers: false, purchases: false, expenses: true, priceUpdates: false, stockAdjustments: false }
  },
  {
    id: "usr-13",
    userId: "u-13",
    name: "Kofi Annan",
    fullName: "Kofi Annan",
    email: "kofi.a@thinksales.com",
    phone: "+233 26 777 8899",
    employeeId: "TS-EMP-013",
    avatarUrl: null,
    role: "manager",
    roleLabel: "Manager",
    status: "pending",
    department: "Operations & Logistics",
    locationId: "b-accra",
    locationName: "Accra Main Branch",
    secondaryBranches: ["b-tema"],
    secondaryBranchNames: ["Tema Branch"],
    lastSignInAt: null,
    joinedAt: "2024-05-24T14:00:00Z",
    isSelf: false,
    twoFactorEnabled: false,
    branchScope: "assigned",
    approvalPermissions: { stockTransfers: true, purchases: true, expenses: true, priceUpdates: false, stockAdjustments: true }
  },
  {
    id: "usr-14",
    userId: "u-14",
    name: "Faustina Arthur",
    fullName: "Faustina Arthur",
    email: "faustina.a@thinksales.com",
    phone: "+233 24 555 6677",
    employeeId: "TS-EMP-014",
    avatarUrl: null,
    role: "cashier",
    roleLabel: "Cashier",
    status: "suspended",
    department: "Sales & Marketing",
    locationId: "b-kumasi",
    locationName: "Kumasi Branch",
    secondaryBranches: [],
    secondaryBranchNames: [],
    lastSignInAt: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
    joinedAt: "2024-02-28T10:00:00Z",
    isSelf: false,
    twoFactorEnabled: false,
    branchScope: "single",
    approvalPermissions: { stockTransfers: false, purchases: false, expenses: false, priceUpdates: false, stockAdjustments: false }
  }
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "log-1",
    userId: "usr-01",
    userName: "John Doe",
    userEmail: "john.doe@thinksales.com",
    action: "User Added",
    module: "User Management",
    timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    branch: "Head Office",
    device: "Chrome 124 (Windows 11)",
    ipAddress: "102.176.94.12",
    status: "success",
    details: "Invited Kofi Annan (kofi.a@thinksales.com) as Manager to Accra Main Branch"
  },
  {
    id: "log-2",
    userId: "usr-01",
    userName: "John Doe",
    userEmail: "john.doe@thinksales.com",
    action: "Role Changed",
    module: "User Management",
    timestamp: new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    branch: "Head Office",
    device: "Chrome 124 (Windows 11)",
    ipAddress: "102.176.94.12",
    status: "success",
    details: "Changed role of Mary Addo from Sales Associate to Manager"
  },
  {
    id: "log-3",
    userId: "usr-02",
    userName: "Mary Addo",
    userEmail: "mary.addo@thinksales.com",
    action: "Approval Granted",
    module: "Transfers",
    timestamp: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    branch: "Kumasi Branch",
    device: "Safari 17.4 (macOS Sonoma)",
    ipAddress: "197.251.130.45",
    status: "success",
    details: "Approved Inter-Branch Stock Transfer TRF-2025-089 (50 units Beverages to Sunyani)"
  },
  {
    id: "log-4",
    userId: "usr-11",
    userName: "Kwame Nkrumah",
    userEmail: "kwame.n@thinksales.com",
    action: "Permission Updated",
    module: "Expenses",
    timestamp: new Date(Date.now() - 1000 * 60 * 280).toISOString(),
    branch: "Head Office",
    device: "Edge 124 (Windows 11)",
    ipAddress: "102.176.94.18",
    status: "success",
    details: "Configured expense approval limit for Accra Main Branch to GHS 25,000"
  },
  {
    id: "log-5",
    userId: "usr-14",
    userName: "Faustina Arthur",
    userEmail: "faustina.a@thinksales.com",
    action: "Failed Login Attempt",
    module: "Authentication",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    branch: "Kumasi Branch",
    device: "Firefox 125 (Windows 10)",
    ipAddress: "41.215.160.22",
    status: "failed",
    details: "3 consecutive invalid password attempts. Account flagged for temporary freeze."
  },
  {
    id: "log-6",
    userId: "usr-01",
    userName: "John Doe",
    userEmail: "john.doe@thinksales.com",
    action: "User Deactivated",
    module: "User Management",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    branch: "Head Office",
    device: "Chrome 124 (Windows 11)",
    ipAddress: "102.176.94.12",
    status: "warning",
    details: "Temporarily suspended Faustina Arthur (Cashier) pending security verification"
  },
  {
    id: "log-7",
    userId: "usr-01",
    userName: "John Doe",
    userEmail: "john.doe@thinksales.com",
    action: "2FA Enforced",
    module: "Security",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    branch: "Head Office",
    device: "Chrome 124 (Windows 11)",
    ipAddress: "102.176.94.12",
    status: "success",
    details: "Enforced mandatory Two-Factor Authentication for all Administrator and Manager accounts"
  },
  {
    id: "log-8",
    userId: "usr-03",
    userName: "Daniel K.",
    userEmail: "daniel.k@thinksales.com",
    action: "Password Reset",
    module: "Authentication",
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    branch: "Takoradi Branch",
    device: "Chrome Mobile (Android 14)",
    ipAddress: "154.160.22.89",
    status: "success",
    details: "Password successfully updated via self-service recovery link"
  }
];
