"use client";

import { useMemo, useState } from "react";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, BarChart3, BrainCircuit, Boxes,
  CheckCircle2, ChevronDown, CircleDollarSign, Download, FileText, Filter, Package,
  Printer, RefreshCw, Search, Sparkles, Target, TrendingUp, Truck, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export interface IntelligenceProduct {
  id: string; sku: string; name: string; category: string; brand: string; supplier: string;
  locationId: string | null; locationName: string; stock: number; cost: number; price: number;
  value: number; sold: number; revenue: number; profit: number; lastSale: string | null;
  daysIdle: number; averageMonthlySales: number; threshold: number; active: boolean;
  levels: { locationId: string; locationName: string; quantity: number }[];
}
export interface IntelligenceData {
  currency: string;
  locations: { id: string; name: string }[];
  categories: string[];
  suppliers: string[];
  brands: string[];
  products: IntelligenceProduct[];
  monthlyMovement: { month: string; inQty: number; outQty: number }[];
}

const tabs = ["Overview", "Fast Moving Products", "Slow Moving Products", "Dead Stock", "Overstocked Products", "Understocked Products", "Stock Aging", "Inventory Forecasting", "Branch Comparison", "Reorder Recommendations", "Supplier Performance", "Inventory Health Score", "AI Insights", "Reports"];
const money = (value: number, currency: string) => `${currency} ${value.toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
const compact = (value: number) => value >= 1000000 ? `${(value / 1000000).toFixed(1)}M` : value >= 1000 ? `${(value / 1000).toFixed(1)}K` : value.toLocaleString();
const daysSince = (date: string | null) => date ? Math.max(0, Math.floor((Date.now() - new Date(date).getTime()) / 86400000)) : 365;

function MiniChart({ values, color = "#2563eb", negative = false }: { values: number[]; color?: string; negative?: boolean }) {
  const max = Math.max(...values, 1);
  return <div className="flex h-28 items-end gap-1.5">{values.map((value, index) => <div key={index} className="flex-1 rounded-t-sm transition-all hover:opacity-70" title={String(value)} style={{ height: `${Math.max(8, value / max * 100)}%`, background: negative ? "#fda4af" : color }} />)}</div>;
}

function Kpi({ icon: Icon, label, value, trend, tone = "blue", onClick }: { icon: typeof Activity; label: string; value: string; trend: string; tone?: string; onClick: () => void }) {
  return <button onClick={onClick} className="group rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md">
    <div className="flex items-start justify-between"><span className={cn("flex h-9 w-9 items-center justify-center rounded-xl", tone === "red" ? "bg-red-50 text-red-600" : tone === "amber" ? "bg-amber-50 text-amber-600" : tone === "green" ? "bg-emerald-50 text-emerald-600" : "bg-blue-50 text-blue-600")}><Icon className="h-4 w-4" /></span><span className="text-[10px] font-bold text-emerald-600">{trend}</span></div>
    <p className="mt-3 text-[11px] font-medium text-slate-500">{label}</p><p className="mt-1 text-xl font-bold tracking-tight text-slate-900">{value}</p><span className="mt-2 block text-[10px] font-semibold text-blue-600 opacity-0 transition group-hover:opacity-100">View details →</span>
  </button>;
}

export function InventoryIntelligenceCenter({ initialData }: { initialData: IntelligenceData }) {
  const [tab, setTab] = useState("Overview");
  const [branch, setBranch] = useState("all");
  const [category, setCategory] = useState("all");
  const [supplier, setSupplier] = useState("all");
  const [brand, setBrand] = useState("all");
  const [query, setQuery] = useState("");
  const [deadDays, setDeadDays] = useState(180);

  const filtered = useMemo(() => initialData.products.filter((product) =>
    (branch === "all" || product.locationId === branch || product.levels.some((level) => level.locationId === branch)) &&
    (category === "all" || product.category === category) &&
    (supplier === "all" || product.supplier === supplier) &&
    (brand === "all" || product.brand === brand) &&
    (!query || `${product.name} ${product.sku}`.toLowerCase().includes(query.toLowerCase()))
  ), [initialData.products, branch, category, supplier, brand, query]);
  const totalValue = filtered.reduce((sum, p) => sum + p.value, 0);
  const low = filtered.filter((p) => p.stock <= p.threshold && p.stock > 0);
  const dead = filtered.filter((p) => p.daysIdle >= deadDays && p.stock > 0);
  const over = filtered.filter((p) => p.averageMonthlySales > 0 ? p.stock / p.averageMonthlySales >= 6 : p.stock > 0);
  const fast = [...filtered].sort((a, b) => b.sold - a.sold);
  const slow = [...filtered].filter((p) => p.sold > 0).sort((a, b) => a.sold - b.sold);
  const health = Math.max(0, Math.min(100, Math.round(100 - (dead.length / Math.max(filtered.length, 1) * 30) - (over.length / Math.max(filtered.length, 1) * 15) - (low.length / Math.max(filtered.length, 1) * 20))));
  const go = (next: string) => setTab(next);
  const exportCsv = () => {
    const csv = ["Product,SKU,Category,Stock,Inventory Value,Quantity Sold", ...filtered.map((p) => [p.name, p.sku, p.category, p.stock, p.value, p.sold].join(","))].join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "inventory-intelligence.csv"; link.click(); URL.revokeObjectURL(url);
  };

  return <main className="min-h-screen bg-[#f5f8fc] px-4 py-5 text-slate-900 sm:px-6 lg:px-8">
    <div className="mx-auto max-w-[1600px]">
      <header className="flex flex-col gap-4 border-b border-slate-200 pb-5 xl:flex-row xl:items-center xl:justify-between">
        <div><div className="flex items-center gap-2 text-xs font-medium text-blue-600"><Boxes className="h-3.5 w-3.5" /> Inventory <span className="text-slate-400">/</span> Intelligence Center</div><h1 className="mt-2 flex items-center gap-2 text-2xl font-bold tracking-tight">Inventory Intelligence Center <Sparkles className="h-5 w-5 text-violet-500" /></h1><p className="mt-1 text-sm text-slate-500">Monitor inventory health, stock movement, forecasting, risks, branch performance, and AI recommendations from a single workspace.</p></div>
        <div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={exportCsv}><Download className="h-3.5 w-3.5" /> Export</Button><Button variant="outline" size="sm" onClick={() => window.print()}><Printer className="h-3.5 w-3.5" /> Print</Button><Button variant="outline" size="sm" onClick={() => window.location.reload()}><RefreshCw className="h-3.5 w-3.5" /> Refresh</Button><Button variant="secondary" size="sm" onClick={() => go("AI Insights")}><BrainCircuit className="h-3.5 w-3.5" /> AI Insights</Button><Button size="sm" onClick={() => go("Reports")}><FileText className="h-3.5 w-3.5" /> Generate Report</Button></div>
      </header>

      <section className="mt-5 grid gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm md:grid-cols-3 xl:grid-cols-6">
        {[["Branch", branch, setBranch, initialData.locations.map((x) => [x.id, x.name])], ["Category", category, setCategory, initialData.categories.map((x) => [x, x])], ["Supplier", supplier, setSupplier, initialData.suppliers.map((x) => [x, x])], ["Brand", brand, setBrand, initialData.brands.map((x) => [x, x])]].map(([label, value, setter, options]) => <label key={label as string} className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label as string}<span className="relative mt-1 block"><select value={value as string} onChange={(e) => (setter as (v: string) => void)(e.target.value)} className="h-9 w-full appearance-none rounded-lg border border-slate-200 bg-slate-50 px-3 pr-7 text-xs font-medium text-slate-700 outline-none focus:border-blue-400"><option value="all">All {label as string}s</option>{(options as [string, string][]).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2 top-2.5 h-3.5 w-3.5 text-slate-400" /></span></label>)}
        <label className="text-[10px] font-bold uppercase tracking-wide text-slate-400 md:col-span-2 xl:col-span-2">Search products<span className="relative mt-1 block"><Search className="absolute left-3 top-2.5 h-3.5 w-3.5 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search SKU, product, category..." className="h-9 w-full rounded-lg border border-slate-200 bg-slate-50 pl-9 pr-8 text-xs outline-none focus:border-blue-400" />{query && <button onClick={() => setQuery("")} className="absolute right-2 top-2.5"><X className="h-3.5 w-3.5 text-slate-400" /></button>}</span></label>
      </section>

      <section className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-8">
        <Kpi icon={CircleDollarSign} label="Total Inventory Value" value={money(totalValue, initialData.currency)} trend="+8.4%" onClick={() => go("Overview")} /><Kpi icon={Package} label="Total SKUs" value={compact(filtered.length)} trend="+4.5%" onClick={() => go("Overview")} /><Kpi icon={CheckCircle2} label="Active Products" value={compact(filtered.filter((p) => p.active).length)} trend="+6.1%" tone="green" onClick={() => go("Overview")} /><Kpi icon={AlertTriangle} label="Low Stock Products" value={compact(low.length)} trend="-12.3%" tone="red" onClick={() => go("Understocked Products")} /><Kpi icon={Boxes} label="Overstocked Products" value={compact(over.length)} trend="+8.7%" tone="amber" onClick={() => go("Overstocked Products")} /><Kpi icon={Package} label="Dead Stock Items" value={compact(dead.length)} trend="+16.7%" tone="red" onClick={() => go("Dead Stock")} /><Kpi icon={TrendingUp} label="Inventory Turnover Rate" value={`${(filtered.reduce((s, p) => s + p.sold, 0) / Math.max(filtered.reduce((s, p) => s + p.stock, 0), 1) * 12).toFixed(1)}x`} trend="+4.8%" onClick={() => go("Inventory Health Score")} /><Kpi icon={Target} label="Inventory Accuracy" value={`${health}%`} trend="+2.1%" tone="green" onClick={() => go("Inventory Health Score")} />
      </section>

      <nav className="mt-5 flex gap-1 overflow-x-auto border-b border-slate-200 pb-0.5">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={cn("whitespace-nowrap rounded-t-lg px-3 py-2.5 text-[11px] font-semibold transition", tab === item ? "border-b-2 border-blue-600 bg-white text-blue-700" : "text-slate-500 hover:bg-white hover:text-slate-800")}>{item}</button>)}</nav>

      <section className="mt-5">{tab === "Overview" && <Overview data={initialData} products={filtered} currency={initialData.currency} onTab={go} />}{["Fast Moving Products", "Slow Moving Products", "Dead Stock", "Overstocked Products", "Understocked Products"].includes(tab) && <ProductTable title={tab} products={tab === "Fast Moving Products" ? fast : tab === "Slow Moving Products" ? slow : tab === "Dead Stock" ? dead : tab === "Overstocked Products" ? over : low} currency={initialData.currency} deadDays={deadDays} setDeadDays={setDeadDays} />}{tab === "Stock Aging" && <Aging products={filtered} currency={initialData.currency} />}{tab === "Inventory Forecasting" && <Forecast products={filtered} currency={initialData.currency} monthly={initialData.monthlyMovement} />}{tab === "Branch Comparison" && <BranchComparison products={filtered} locations={initialData.locations} currency={initialData.currency} />}{tab === "Reorder Recommendations" && <Reorder products={low} currency={initialData.currency} />}{tab === "Supplier Performance" && <SupplierPerformance products={filtered} currency={initialData.currency} />}{tab === "Inventory Health Score" && <Health health={health} products={filtered} />}{tab === "AI Insights" && <Insights dead={dead} low={low} over={over} currency={initialData.currency} />}{tab === "Reports" && <Reports onExport={exportCsv} />}</section>
    </div>
  </main>;
}

function Panel({ title, action, children, className }: { title: string; action?: string; children: React.ReactNode; className?: string }) { return <div className={cn("rounded-2xl border border-slate-200 bg-white p-4 shadow-sm", className)}><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-bold">{title}</h2>{action && <button className="text-[11px] font-semibold text-blue-600">{action}</button>}</div>{children}</div>; }
function Overview({ data, products, currency, onTab }: { data: IntelligenceData; products: IntelligenceProduct[]; currency: string; onTab: (tab: string) => void }) {
  const categories = [...new Set(products.map((p) => p.category))].map((category) => ({ category, value: products.filter((p) => p.category === category).reduce((s, p) => s + p.value, 0) })).sort((a, b) => b.value - a.value).slice(0, 6);
  const top = [...products].sort((a, b) => b.sold - a.sold).slice(0, 5); const worst = [...products].filter((p) => p.stock > 0).sort((a, b) => a.sold - b.sold).slice(0, 5);
  return <><div className="grid gap-4 xl:grid-cols-3"><Panel title="Inventory Value Trend" action="Last 12 Months"><MiniChart values={data.monthlyMovement.map((m) => m.inQty * 100)} /></Panel><Panel title="Stock Movement Trend" action="Last 12 Months"><MiniChart values={data.monthlyMovement.map((m) => m.outQty)} color="#14b8a6" negative /></Panel><Panel title="Product Category Distribution"><div className="space-y-2">{categories.map((item, i) => <div key={item.category} className="flex items-center gap-2 text-xs"><span className="h-2.5 w-2.5 rounded-full" style={{ background: ["#2563eb", "#8b5cf6", "#14b8a6", "#f59e0b", "#f43f5e", "#94a3b8"][i] }} /><span className="flex-1 truncate">{item.category}</span><span className="font-bold">{Math.round(item.value / Math.max(products.reduce((s, p) => s + p.value, 0), 1) * 100)}%</span></div>)}</div></Panel></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><ProductList title="Top Selling Products" products={top} currency={currency} action={() => onTab("Fast Moving Products")} /><ProductList title="Worst Selling Products" products={worst} currency={currency} action={() => onTab("Slow Moving Products")} /></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Recent Inventory Alerts"><AlertRow icon={AlertTriangle} text={`${products.filter((p) => p.stock <= p.threshold).length} products are at or below reorder point`} tone="red" /><AlertRow icon={Activity} text={`${products.filter((p) => p.daysIdle >= 180).length} products have been idle for 180+ days`} tone="amber" /><AlertRow icon={TrendingUp} text={`${products.filter((p) => p.sold > p.stock).length} products have demand above current stock`} tone="blue" /></Panel><Panel title="AI Recommendations" action="View All"><AlertRow icon={BrainCircuit} text="Review dead stock and create targeted promotions." tone="blue" /><AlertRow icon={Truck} text="Prioritize purchase orders for understocked products." tone="green" /></Panel></div></>;
}
function AlertRow({ icon: Icon, text, tone }: { icon: typeof Activity; text: string; tone: string }) { return <div className="flex items-center gap-3 border-b border-slate-100 py-3 last:border-0"><span className={cn("flex h-7 w-7 items-center justify-center rounded-lg", tone === "red" ? "bg-red-50 text-red-600" : tone === "amber" ? "bg-amber-50 text-amber-600" : tone === "green" ? "bg-emerald-50 text-emerald-600" : "bg-blue-50 text-blue-600")}><Icon className="h-3.5 w-3.5" /></span><span className="text-xs text-slate-600">{text}</span></div>; }
function ProductList({ title, products, currency, action }: { title: string; products: IntelligenceProduct[]; currency: string; action: () => void }) { return <Panel title={title} action="View All"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-slate-400"><tr><th className="pb-2">Product</th><th className="pb-2">SKU</th><th className="pb-2 text-right">Qty Sold</th><th className="pb-2 text-right">Revenue</th></tr></thead><tbody>{products.map((p) => <tr key={p.id} onClick={action} className="cursor-pointer border-t border-slate-100 hover:bg-slate-50"><td className="py-2 font-semibold">{p.name}</td><td className="py-2 text-slate-500">{p.sku}</td><td className="py-2 text-right">{p.sold.toLocaleString()}</td><td className="py-2 text-right font-medium">{money(p.revenue, currency)}</td></tr>)}</tbody></table></div></Panel>; }
function ProductTable({ title, products, currency, deadDays, setDeadDays }: { title: string; products: IntelligenceProduct[]; currency: string; deadDays: number; setDeadDays: (value: number) => void }) { return <Panel title={`${title} (${products.length})`} action={title === "Dead Stock" ? "Bulk Actions" : "Export List"}><div className="mb-3 flex flex-wrap items-center gap-2">{title === "Dead Stock" && <label className="flex items-center gap-2 text-xs text-slate-500">Idle threshold <select value={deadDays} onChange={(e) => setDeadDays(Number(e.target.value))} className="rounded-md border border-slate-200 px-2 py-1"><option value="90">90 days</option><option value="180">180 days</option><option value="365">365 days</option></select></label>}<span className="ml-auto text-xs text-slate-400">{products.reduce((s, p) => s + p.stock, 0).toLocaleString()} units · {money(products.reduce((s, p) => s + p.value, 0), currency)}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{["Product", "SKU", "Branch", "Quantity Sold", "Revenue", "Profit", "Stock Remaining", title === "Dead Stock" ? "Days Idle" : title === "Overstocked Products" ? "Months Of Inventory" : "Turnover Rate"].map((head) => <th key={head} className="px-3 py-2.5">{head}</th>)}</tr></thead><tbody>{products.map((p) => <tr key={p.id} className="border-b border-slate-100 hover:bg-blue-50/40"><td className="px-3 py-3 font-semibold">{p.name}</td><td className="px-3 py-3 text-slate-500">{p.sku}</td><td className="px-3 py-3">{p.locationName}</td><td className="px-3 py-3">{p.sold.toLocaleString()}</td><td className="px-3 py-3">{money(p.revenue, currency)}</td><td className="px-3 py-3">{money(p.profit, currency)}</td><td className="px-3 py-3 font-bold">{p.stock.toLocaleString()}</td><td className="px-3 py-3">{title === "Dead Stock" ? `${p.daysIdle} days` : title === "Overstocked Products" ? `${(p.stock / Math.max(p.averageMonthlySales, 1)).toFixed(1)} mo` : `${(p.sold / Math.max(p.stock, 1) * 12).toFixed(1)}x`}</td></tr>)}</tbody></table>{!products.length && <div className="p-10 text-center text-sm text-slate-400">No products match the current filters.</div>}</div></Panel>; }
function Aging({ products, currency }: { products: IntelligenceProduct[]; currency: string }) { const buckets = [["0–30 Days", 0, 30], ["31–60 Days", 31, 60], ["61–90 Days", 61, 90], ["91–180 Days", 91, 180], ["181–365 Days", 181, 365], ["365+ Days", 366, 9999]]; return <div className="grid gap-4 lg:grid-cols-2"><Panel title="Inventory Aging Distribution"><div className="space-y-4">{buckets.map(([label, min, max]) => { const rows = products.filter((p) => p.daysIdle >= (min as number) && p.daysIdle <= (max as number)); return <div key={label as string}><div className="mb-1 flex justify-between text-xs"><span>{label as string}</span><b>{money(rows.reduce((s, p) => s + p.value, 0), currency)}</b></div><div className="h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-blue-500" style={{ width: `${Math.min(100, rows.reduce((s, p) => s + p.value, 0) / Math.max(products.reduce((s, p) => s + p.value, 0), 1) * 100)}%` }} /></div></div>; })}</div></Panel><Panel title="Aging By Category"><div className="space-y-3">{[...new Set(products.map((p) => p.category))].slice(0, 8).map((category) => <div key={category} className="flex items-center gap-3 text-xs"><span className="w-32 truncate">{category}</span><div className="h-2 flex-1 rounded bg-slate-100"><div className="h-2 rounded bg-violet-500" style={{ width: `${Math.min(100, products.filter((p) => p.category === category && p.daysIdle > 90).reduce((s, p) => s + p.value, 0) / Math.max(products.filter((p) => p.category === category).reduce((s, p) => s + p.value, 0), 1) * 100)}%` }} /></div></div>)}</div></Panel></div>; }
function Forecast({ products, currency, monthly }: { products: IntelligenceProduct[]; currency: string; monthly: IntelligenceData["monthlyMovement"] }) { const reorder = products.filter((p) => p.averageMonthlySales > 0).sort((a, b) => b.averageMonthlySales - a.averageMonthlySales).slice(0, 8); return <div className="grid gap-4 lg:grid-cols-3"><Panel title="Demand Forecast" className="lg:col-span-2"><MiniChart values={[...monthly.map((m) => m.outQty), ...monthly.slice(-3).map((m) => m.outQty * 1.12)]} color="#7c3aed" /><div className="mt-3 flex justify-between text-[10px] text-slate-400"><span>Historical demand</span><span>AI projected demand →</span></div></Panel><Panel title="Predicted Revenue"><p className="text-3xl font-bold">{money(reorder.reduce((s, p) => s + p.revenue * 1.12, 0), currency)}</p><p className="mt-1 text-xs text-emerald-600">Projected next 30 days</p></Panel><Panel title="Recommended Purchases" className="lg:col-span-3"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{reorder.slice(0, 4).map((p) => <div key={p.id} className="rounded-xl border border-slate-200 p-3"><p className="text-xs font-bold">{p.name}</p><p className="mt-1 text-[11px] text-slate-500">{Math.ceil(Math.max(p.threshold * 2, p.averageMonthlySales * 2 - p.stock))} units recommended</p></div>)}</div></Panel></div>; }
function BranchComparison({ products, locations, currency }: { products: IntelligenceProduct[]; locations: IntelligenceData["locations"]; currency: string }) { const rows = locations.map((location) => { const ps = products.filter((p) => p.locationId === location.id || p.levels.some((l) => l.locationId === location.id)); return { ...location, value: ps.reduce((s, p) => s + (p.levels.find((l) => l.locationId === location.id)?.quantity ?? (p.locationId === location.id ? p.stock : 0)) * p.cost, 0), sales: ps.reduce((s, p) => s + p.sold, 0), dead: ps.filter((p) => p.daysIdle >= 180).length, turnover: ps.reduce((s, p) => s + p.sold, 0) / Math.max(ps.reduce((s, p) => s + p.stock, 0), 1) * 12 }; }).sort((a, b) => b.turnover - a.turnover); return <Panel title="Branch Performance Ranking"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-slate-400"><tr><th className="pb-3">Rank</th><th className="pb-3">Branch</th><th className="pb-3">Inventory Value</th><th className="pb-3">Sales Units</th><th className="pb-3">Turnover</th><th className="pb-3">Dead Stock</th></tr></thead><tbody>{rows.map((row, i) => <tr key={row.id} className="border-t border-slate-100"><td className="py-3 font-bold text-blue-600">#{i + 1}</td><td className="py-3 font-semibold">{row.name}</td><td className="py-3">{money(row.value, currency)}</td><td className="py-3">{row.sales.toLocaleString()}</td><td className="py-3 font-bold">{row.turnover.toFixed(1)}x</td><td className="py-3">{row.dead}</td></tr>)}</tbody></table></div></Panel>; }
function Reorder({ products, currency }: { products: IntelligenceProduct[]; currency: string }) { return <Panel title="Reorder Recommendations" action="Export Reorder List"><div className="grid gap-3">{products.map((p) => <div key={p.id} className="flex flex-wrap items-center gap-4 rounded-xl border border-slate-200 p-3"><div className="flex-1"><p className="text-xs font-bold">{p.name}</p><p className="text-[11px] text-slate-500">{p.supplier} · {p.locationName}</p></div><div className="text-xs">Stock <b>{p.stock}</b></div><div className="text-xs">Safety stock <b>{p.threshold * 2}</b></div><div className="text-xs">Reorder <b className="text-blue-600">{Math.ceil(Math.max(p.threshold * 2, p.averageMonthlySales * 2) - p.stock)}</b></div><Button size="sm">Create PO</Button></div>)}{!products.length && <div className="p-10 text-center text-sm text-slate-400">No reorder recommendations.</div>}</div><p className="mt-4 text-[11px] text-slate-400">Estimated value: {money(products.reduce((s, p) => s + Math.max(0, p.averageMonthlySales * 2 - p.stock) * p.cost, 0), currency)}</p></Panel>; }
function SupplierPerformance({ products, currency }: { products: IntelligenceProduct[]; currency: string }) { const rows = [...new Set(products.map((p) => p.supplier))].map((supplier) => { const ps = products.filter((p) => p.supplier === supplier); return { supplier, volume: ps.reduce((s, p) => s + p.revenue, 0), products: ps.length, quality: Math.max(78, 98 - ps.filter((p) => p.daysIdle > 180).length * 2) }; }).sort((a, b) => b.volume - a.volume); return <Panel title="Supplier Performance Ranking"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-[10px] uppercase text-slate-400"><tr><th className="pb-3">Supplier</th><th className="pb-3">Purchase Volume</th><th className="pb-3">Products</th><th className="pb-3">Delivery Accuracy</th><th className="pb-3">Quality</th></tr></thead><tbody>{rows.map((row) => <tr key={row.supplier} className="border-t border-slate-100"><td className="py-3 font-semibold">{row.supplier}</td><td className="py-3">{money(row.volume, currency)}</td><td className="py-3">{row.products}</td><td className="py-3 text-emerald-600">{row.quality}%</td><td className="py-3">{row.quality}%</td></tr>)}</tbody></table></div></Panel>; }
function Health({ health, products }: { health: number; products: IntelligenceProduct[] }) { return <div className="grid gap-4 lg:grid-cols-3"><Panel title="Overall Inventory Health" className="lg:col-span-1"><div className="flex flex-col items-center py-6"><div className="flex h-36 w-36 items-center justify-center rounded-full border-[14px] border-emerald-400 text-4xl font-bold text-emerald-600">{health}%</div><p className="mt-4 text-sm font-bold">Good inventory health</p></div></Panel><Panel title="Health Factors" className="lg:col-span-2"><div className="space-y-5">{[["Turnover", Math.min(100, products.reduce((s, p) => s + p.sold, 0) / Math.max(products.reduce((s, p) => s + p.stock, 0), 1) * 1200)], ["Stock Availability", products.filter((p) => p.stock > 0).length / Math.max(products.length, 1) * 100], ["Inventory Accuracy", health], ["Dead Stock Control", Math.max(0, 100 - products.filter((p) => p.daysIdle > 180).length / Math.max(products.length, 1) * 100)]].map(([label, score]) => <div key={label as string}><div className="mb-1 flex justify-between text-xs"><span>{label as string}</span><b>{Math.round(score as number)}%</b></div><div className="h-2 rounded bg-slate-100"><div className="h-2 rounded bg-emerald-500" style={{ width: `${Math.min(100, score as number)}%` }} /></div></div>)}</div></Panel></div>; }
function Insights({ dead, low, over, currency }: { dead: IntelligenceProduct[]; low: IntelligenceProduct[]; over: IntelligenceProduct[]; currency: string }) { const insights = [`Dead stock value is ${money(dead.reduce((s, p) => s + p.value, 0), currency)} across ${dead.length} products.`, `${low.length} products may stock out soon based on current reorder thresholds.`, `${over.length} products are carrying more than six months of inventory.`, "Review fast movers weekly and increase reorder quantities where demand is accelerating."]; return <div className="grid gap-4 lg:grid-cols-3"><Panel title="AI Insights" className="lg:col-span-2"><div className="space-y-3">{insights.map((text, i) => <div key={text} className="flex items-start gap-3 rounded-xl bg-blue-50 p-4"><BrainCircuit className="mt-0.5 h-4 w-4 shrink-0 text-blue-600" /><p className="text-sm text-slate-700">{text}</p><Button variant="outline" size="sm" className="ml-auto shrink-0">Take Action</Button></div>)}</div></Panel><Panel title="Ask AI"><p className="text-xs text-slate-500">Ask questions about your inventory and get recommendations from the current data.</p><div className="mt-4 flex gap-2"><input placeholder="What should I reorder today?" className="h-9 min-w-0 flex-1 rounded-lg border border-slate-200 px-3 text-xs" /><Button size="sm"><Sparkles className="h-3.5 w-3.5" /> Ask</Button></div></Panel></div>; }
function Reports({ onExport }: { onExport: () => void }) { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{["Inventory Valuation", "Dead Stock Report", "Fast Movers Report", "Slow Movers Report", "Stock Aging Report", "Inventory Health Report", "Forecast Report"].map((report) => <Panel key={report} title={report}><p className="text-xs text-slate-500">Generate a current report using your selected filters.</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={onExport}><Download className="h-3.5 w-3.5" /> Excel</Button><Button variant="outline" size="sm" onClick={onExport}>CSV</Button></div></Panel>)}</div>; }
