begin;

create table public.branch_product_returns (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  return_number bigint generated by default as identity,
  source_location_id uuid not null references public.business_locations(id),
  destination_location_id uuid not null references public.business_locations(id),
  return_date date not null default current_date,
  requested_by uuid not null references auth.users(id),
  created_by uuid not null references auth.users(id),
  status text not null default 'pending_review'
    check (status in ('pending_review', 'pending_identification', 'identified', 'consolidated', 'supplier_return_created', 'completed', 'rejected', 'cancelled')),
  return_reason text not null,
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (org_id, return_number),
  check (source_location_id <> destination_location_id)
);

create table public.branch_product_return_items (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  return_id uuid not null references public.branch_product_returns(id) on delete restrict,
  product_id uuid not null references public.products(id),
  return_qty integer not null check (return_qty > 0),
  unit_cost numeric(12, 2) not null check (unit_cost >= 0),
  return_value numeric(14, 2) not null check (return_value >= 0),
  condition text not null,
  return_reason text not null,
  inspection_notes text,
  original_transfer_id uuid references public.stock_transfers(id),
  supplier_id uuid references public.suppliers(id),
  purchase_id uuid references public.purchases(id),
  purchase_item_id uuid references public.purchase_items(id),
  supplier_accepted_qty integer,
  supplier_rejected_qty integer,
  supplier_response_notes text,
  created_at timestamptz not null default now(),
  check ((supplier_id is null and purchase_id is null and purchase_item_id is null)
    or (supplier_id is not null and purchase_id is not null and purchase_item_id is not null)),
  check (supplier_accepted_qty is null or supplier_accepted_qty >= 0),
  check (supplier_rejected_qty is null or supplier_rejected_qty >= 0)
);

create table public.branch_product_return_consolidations (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  consolidation_number bigint generated by default as identity,
  supplier_id uuid not null references public.suppliers(id),
  purchase_id uuid not null references public.purchases(id),
  status text not null default 'ready'
    check (status in ('ready', 'supplier_return_created', 'accepted', 'partially_accepted', 'rejected', 'completed')),
  purchase_return_id uuid references public.purchase_returns(id),
  supplier_accepted_qty integer,
  supplier_rejected_qty integer,
  supplier_response_notes text,
  supplier_responded_by uuid references auth.users(id),
  supplier_responded_at timestamptz,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  unique (org_id, consolidation_number),
  check (supplier_accepted_qty is null or supplier_accepted_qty >= 0),
  check (supplier_rejected_qty is null or supplier_rejected_qty >= 0)
);

create table public.branch_product_return_consolidation_items (
  consolidation_id uuid not null references public.branch_product_return_consolidations(id) on delete restrict,
  return_item_id uuid not null unique references public.branch_product_return_items(id) on delete restrict,
  org_id uuid not null references public.organizations(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (consolidation_id, return_item_id)
);

create table public.branch_product_return_attachments (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  return_id uuid not null references public.branch_product_returns(id) on delete restrict,
  storage_path text not null unique,
  file_name text not null,
  content_type text not null,
  file_size bigint not null check (file_size > 0 and file_size <= 5242880),
  uploaded_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create index branch_product_returns_org_created_idx
  on public.branch_product_returns(org_id, created_at desc);
create index branch_product_returns_location_date_idx
  on public.branch_product_returns(org_id, source_location_id, return_date desc);
create index branch_product_returns_status_idx
  on public.branch_product_returns(org_id, status, created_at desc);
create index branch_product_return_items_return_idx
  on public.branch_product_return_items(return_id);
create index branch_product_return_items_product_idx
  on public.branch_product_return_items(org_id, product_id, created_at desc);
create index branch_product_return_items_supplier_idx
  on public.branch_product_return_items(org_id, supplier_id, purchase_id);
create index branch_product_return_consolidations_org_idx
  on public.branch_product_return_consolidations(org_id, created_at desc);
create index branch_product_return_attachments_return_idx
  on public.branch_product_return_attachments(org_id, return_id, created_at desc);

alter table public.branch_product_returns enable row level security;
alter table public.branch_product_return_items enable row level security;
alter table public.branch_product_return_consolidations enable row level security;
alter table public.branch_product_return_consolidation_items enable row level security;
alter table public.branch_product_return_attachments enable row level security;

create policy "branch_product_returns: assigned members can read"
  on public.branch_product_returns for select
  using (
    exists (
      select 1 from public.organization_members m
      where m.org_id = branch_product_returns.org_id
        and m.user_id = auth.uid()
        and m.status = 'active'
        and (
          m.branch_scope = 'all'
          or m.location_id::text = branch_product_returns.source_location_id::text
          or branch_product_returns.source_location_id::text = any(m.secondary_location_ids::text[])
        )
    )
  );

create policy "branch_product_return_items: assigned members can read"
  on public.branch_product_return_items for select
  using (
    exists (
      select 1 from public.branch_product_returns r
      join public.organization_members m on m.org_id = r.org_id
      where r.id = branch_product_return_items.return_id
        and m.user_id = auth.uid()
        and m.status = 'active'
        and (
          m.branch_scope = 'all'
          or m.location_id::text = r.source_location_id::text
          or r.source_location_id::text = any(m.secondary_location_ids::text[])
        )
    )
  );

create policy "branch_product_return_consolidations: central members can read"
  on public.branch_product_return_consolidations for select
  using (
    exists (
      select 1 from public.organization_members m
      where m.org_id = branch_product_return_consolidations.org_id
        and m.user_id = auth.uid()
        and m.status = 'active'
        and m.branch_scope = 'all'
    )
  );

create policy "branch_product_return_consolidation_items: central members can read"
  on public.branch_product_return_consolidation_items for select
  using (
    exists (
      select 1 from public.branch_product_return_consolidations c
      join public.organization_members m on m.org_id = c.org_id
      where c.id = branch_product_return_consolidation_items.consolidation_id
        and m.user_id = auth.uid()
        and m.status = 'active'
        and m.branch_scope = 'all'
    )
  );

create policy "branch_product_return_attachments: assigned members can read"
  on public.branch_product_return_attachments for select
  using (
    exists (
      select 1 from public.branch_product_returns r
      join public.organization_members m on m.org_id = r.org_id
      where r.id = branch_product_return_attachments.return_id
        and m.user_id = auth.uid()
        and m.status = 'active'
        and (
          m.branch_scope = 'all'
          or m.location_id::text = r.source_location_id::text
          or r.source_location_id::text = any(m.secondary_location_ids::text[])
        )
    )
  );

insert into storage.buckets (id, name, public)
values ('branch-return-attachments', 'branch-return-attachments', false)
on conflict (id) do nothing;

create policy "branch return attachments: assigned members upload"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'branch-return-attachments'
    and exists (
      select 1
      from public.branch_product_returns r
      join public.organization_members m on m.org_id = r.org_id
      where r.id = (storage.foldername(name))[2]::uuid
        and r.org_id = (storage.foldername(name))[1]::uuid
        and m.user_id = auth.uid()
        and m.status = 'active'
        and (
          m.branch_scope = 'all'
          or m.location_id::text = r.source_location_id::text
          or r.source_location_id::text = any(m.secondary_location_ids::text[])
        )
    )
  );

create policy "branch return attachments: assigned members read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'branch-return-attachments'
    and exists (
      select 1
      from public.branch_product_returns r
      join public.organization_members m on m.org_id = r.org_id
      where r.id = (storage.foldername(name))[2]::uuid
        and r.org_id = (storage.foldername(name))[1]::uuid
        and m.user_id = auth.uid()
        and m.status = 'active'
        and (
          m.branch_scope = 'all'
          or m.location_id::text = r.source_location_id::text
          or r.source_location_id::text = any(m.secondary_location_ids::text[])
        )
    )
  );

create or replace function public.submit_branch_product_return(
  p_org_id uuid,
  p_actor_id uuid,
  p_source_location_id uuid,
  p_destination_location_id uuid,
  p_return_date date,
  p_return_reason text,
  p_priority text,
  p_notes text,
  p_items jsonb
)
returns table (return_id uuid, return_number bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_member public.organization_members%rowtype;
  v_source public.business_locations%rowtype;
  v_destination public.business_locations%rowtype;
  v_return public.branch_product_returns%rowtype;
  v_line jsonb;
  v_product public.products%rowtype;
  v_stock public.product_stock_levels%rowtype;
  v_qty integer;
  v_transfer_id uuid;
  v_count integer := 0;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Not authorized to submit branch returns';
  end if;

  select * into v_member
  from public.organization_members
  where org_id = p_org_id and user_id = p_actor_id and status = 'active';
  if not found then raise exception 'Active organization membership is required'; end if;

  if v_member.branch_scope <> 'all'
    and p_source_location_id::text is distinct from v_member.location_id::text
    and not (
      p_source_location_id::text = any(coalesce(v_member.secondary_location_ids::text[], '{}'::text[]))
    ) then
    raise exception 'You are not assigned to the selected source branch';
  end if;

  select * into v_source
  from public.business_locations
  where id = p_source_location_id and org_id = p_org_id and is_active;
  if not found then raise exception 'The source branch is unavailable'; end if;

  select * into v_destination
  from public.business_locations
  where id = p_destination_location_id and org_id = p_org_id and is_active
    and location_type in ('warehouse', 'distribution_center');
  if not found or p_destination_location_id = p_source_location_id then
    raise exception 'Choose an active returns warehouse or distribution center';
  end if;

  if p_priority not in ('low', 'normal', 'high', 'urgent') then
    raise exception 'Invalid return priority';
  end if;
  if nullif(trim(p_return_reason), '') is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Return reason and at least one product are required';
  end if;

  insert into public.branch_product_returns (
    org_id, source_location_id, destination_location_id, return_date,
    requested_by, created_by, return_reason, priority, notes
  ) values (
    p_org_id, p_source_location_id, p_destination_location_id,
    coalesce(p_return_date, current_date), p_actor_id, p_actor_id,
    trim(p_return_reason), p_priority, nullif(trim(p_notes), '')
  ) returning * into v_return;

  for v_line in select value from jsonb_array_elements(p_items)
  loop
    v_qty := (v_line->>'quantity')::integer;
    if v_qty <= 0 then raise exception 'Return quantities must be positive whole numbers'; end if;

    select * into v_product from public.products
    where id = (v_line->>'product_id')::uuid
      and org_id = p_org_id
      and is_active
      and track_inventory;
    if not found then raise exception 'A selected product is unavailable for inventory returns'; end if;

    select * into v_stock from public.product_stock_levels
    where org_id = p_org_id and product_id = v_product.id and location_id = p_source_location_id
    for update;
    if not found or v_stock.quantity < v_qty then
      raise exception 'Insufficient branch stock for product %', v_product.name;
    end if;

    v_transfer_id := nullif(v_line->>'transfer_id', '')::uuid;
    if v_transfer_id is not null and not exists (
      select 1
      from public.stock_transfer_items ti
      join public.stock_transfers t on t.id = ti.transfer_id
      where ti.transfer_id = v_transfer_id
        and ti.org_id = p_org_id
        and ti.product_id = v_product.id
        and t.to_location_id = p_source_location_id
        and t.status = 'completed'
    ) then
      raise exception 'The selected source transfer does not match this product and branch';
    end if;

    if nullif(trim(v_line->>'condition'), '') is null
      or nullif(trim(v_line->>'reason'), '') is null then
      raise exception 'Each return item requires a condition and reason';
    end if;

    insert into public.branch_product_return_items (
      org_id, return_id, product_id, return_qty, unit_cost, return_value,
      condition, return_reason, inspection_notes, original_transfer_id
    ) values (
      p_org_id, v_return.id, v_product.id, v_qty,
      coalesce(v_product.cost_price, 0),
      round(coalesce(v_product.cost_price, 0) * v_qty, 2),
      trim(v_line->>'condition'), trim(v_line->>'reason'),
      nullif(trim(v_line->>'inspection_notes'), ''), v_transfer_id
    );

    update public.product_stock_levels
    set quantity = quantity - v_qty, updated_at = now()
    where id = v_stock.id;

    insert into public.product_stock_levels (org_id, product_id, location_id, quantity)
    values (p_org_id, v_product.id, p_destination_location_id, v_qty)
    on conflict (product_id, location_id)
    do update set quantity = public.product_stock_levels.quantity + excluded.quantity, updated_at = now();

    v_count := v_count + 1;
  end loop;

  if v_count = 0 then raise exception 'Add at least one return item'; end if;

  insert into public.audit_logs (org_id, actor_id, action, entity_type, entity_id, metadata)
  values (
    p_org_id, p_actor_id, 'branch_product_return.submitted',
    'branch_product_returns', v_return.id,
    jsonb_build_object(
      'return_number', v_return.return_number,
      'source_location_id', p_source_location_id,
      'destination_location_id', p_destination_location_id,
      'item_count', v_count,
      'module', 'return_products'
    )
  );

  return query select v_return.id, v_return.return_number;
end;
$$;

revoke all on function public.submit_branch_product_return(uuid, uuid, uuid, uuid, date, text, text, text, jsonb) from public, anon, authenticated;
grant execute on function public.submit_branch_product_return(uuid, uuid, uuid, uuid, date, text, text, text, jsonb) to service_role;

create or replace function public.consolidate_branch_product_returns(
  p_org_id uuid,
  p_actor_id uuid,
  p_return_item_ids uuid[]
)
returns table (consolidation_id uuid, consolidation_number bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_supplier_id uuid;
  v_purchase_id uuid;
  v_destination_id uuid;
  v_consolidation public.branch_product_return_consolidations%rowtype;
  v_count integer;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Not authorized to consolidate branch returns';
  end if;
  if not exists (
    select 1 from public.organization_members m
    where m.org_id = p_org_id and m.user_id = p_actor_id
      and m.status = 'active' and m.branch_scope = 'all'
  ) then
    raise exception 'Returns consolidation is restricted to central organization members';
  end if;
  if coalesce(array_length(p_return_item_ids, 1), 0) < 1 then
    raise exception 'Select at least one identified return item';
  end if;

  select count(*), (array_agg(i.supplier_id))[1], (array_agg(i.purchase_id))[1], (array_agg(r.destination_location_id))[1]
    into v_count, v_supplier_id, v_purchase_id, v_destination_id
  from public.branch_product_return_items i
  join public.branch_product_returns r on r.id = i.return_id
  where i.org_id = p_org_id
    and i.id = any(p_return_item_ids)
    and i.supplier_id is not null
    and i.purchase_id is not null
    and i.purchase_item_id is not null
    and r.status = 'identified';

  if v_count <> array_length(p_return_item_ids, 1) then
    raise exception 'Every selected item must be identified and not already consolidated';
  end if;
  if exists (
    select 1 from public.branch_product_return_items i
    where i.id = any(p_return_item_ids)
      and (i.supplier_id is distinct from v_supplier_id or i.purchase_id is distinct from v_purchase_id)
  ) then
    raise exception 'Returns from different suppliers or purchases cannot be consolidated together';
  end if;
  if exists (
    select 1 from public.branch_product_return_items i
    join public.branch_product_returns r on r.id = i.return_id
    where i.id = any(p_return_item_ids) and r.destination_location_id is distinct from v_destination_id
  ) then
    raise exception 'Returns destined for different offices cannot be consolidated together';
  end if;
  if exists (
    select 1 from public.branch_product_return_consolidation_items ci
    where ci.return_item_id = any(p_return_item_ids)
  ) then
    raise exception 'A selected return item has already been consolidated';
  end if;

  insert into public.branch_product_return_consolidations (
    org_id, supplier_id, purchase_id, created_by
  ) values (
    p_org_id, v_supplier_id, v_purchase_id, p_actor_id
  ) returning * into v_consolidation;

  insert into public.branch_product_return_consolidation_items (consolidation_id, return_item_id, org_id)
  select v_consolidation.id, i.id, p_org_id
  from public.branch_product_return_items i
  where i.id = any(p_return_item_ids);

  update public.branch_product_returns r
  set status = 'consolidated', updated_at = now()
  where r.id in (
    select i.return_id from public.branch_product_return_items i where i.id = any(p_return_item_ids)
  )
  and not exists (
    select 1
    from public.branch_product_return_items ri
    left join public.branch_product_return_consolidation_items ci on ci.return_item_id = ri.id
    where ri.return_id = r.id and ci.return_item_id is null
  );

  insert into public.audit_logs (org_id, actor_id, action, entity_type, entity_id, metadata)
  values (
    p_org_id, p_actor_id, 'branch_product_return.consolidated',
    'branch_product_return_consolidations', v_consolidation.id,
    jsonb_build_object('consolidation_number', v_consolidation.consolidation_number, 'item_count', v_count, 'module', 'return_products')
  );

  return query select v_consolidation.id, v_consolidation.consolidation_number;
end;
$$;

revoke all on function public.consolidate_branch_product_returns(uuid, uuid, uuid[]) from public, anon, authenticated;
grant execute on function public.consolidate_branch_product_returns(uuid, uuid, uuid[]) to service_role;

create or replace function public.create_branch_return_purchase_return(
  p_org_id uuid,
  p_actor_id uuid,
  p_consolidation_id uuid
)
returns table (purchase_return_id uuid, purchase_return_number integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_consolidation public.branch_product_return_consolidations%rowtype;
  v_purchase public.purchases%rowtype;
  v_return public.purchase_returns%rowtype;
  v_item record;
  v_destination_id uuid;
  v_line_count integer := 0;
  v_total numeric(14, 2) := 0;
  v_prior_qty numeric;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Not authorized to create supplier returns';
  end if;
  if not exists (
    select 1 from public.organization_members m
    where m.org_id = p_org_id and m.user_id = p_actor_id
      and m.status = 'active' and m.branch_scope = 'all'
  ) then
    raise exception 'Supplier returns are restricted to central organization members';
  end if;
  select * into v_consolidation
  from public.branch_product_return_consolidations
  where id = p_consolidation_id and org_id = p_org_id
  for update;
  if not found or v_consolidation.status <> 'ready' or v_consolidation.purchase_return_id is not null then
    raise exception 'This consolidation is not ready for a supplier return';
  end if;
  select * into v_purchase
  from public.purchases
  where id = v_consolidation.purchase_id
    and org_id = p_org_id
    and supplier_id = v_consolidation.supplier_id
    and status in ('received', 'partially_received');
  if not found then raise exception 'The matched purchase is not available for return'; end if;

  select (array_agg(r.destination_location_id))[1]
  into v_destination_id
  from public.branch_product_return_consolidation_items ci
  join public.branch_product_return_items i on i.id = ci.return_item_id
  join public.branch_product_returns r on r.id = i.return_id
  where ci.consolidation_id = p_consolidation_id and ci.org_id = p_org_id;
  if v_destination_id is null or exists (
    select 1
    from public.branch_product_return_consolidation_items ci
    join public.branch_product_return_items i on i.id = ci.return_item_id
    join public.branch_product_returns r on r.id = i.return_id
    where ci.consolidation_id = p_consolidation_id
      and ci.org_id = p_org_id
      and r.destination_location_id is distinct from v_destination_id
  ) then
    raise exception 'Consolidated items must share one returns office';
  end if;

  insert into public.purchase_returns (
    org_id, purchase_id, supplier_id, location_id, status, return_date,
    return_reason, invoice_number, reference, notes, total_return_value,
    refund_amount, created_by
  ) values (
    p_org_id, v_purchase.id, v_purchase.supplier_id, v_destination_id, 'submitted',
    current_date, 'Branch product return', v_purchase.invoice_number,
    'BR-RET-CON-' || lpad(v_consolidation.consolidation_number::text, 6, '0'),
    'Created from Return Products consolidation #' || v_consolidation.consolidation_number || '.',
    0, 0, p_actor_id
  ) returning * into v_return;

  for v_item in
    select i.id, i.product_id, i.return_qty, i.return_reason, i.condition,
      i.purchase_item_id, pi.quantity_received, pi.unit_price, pi.product_id as purchased_product_id
    from public.branch_product_return_consolidation_items ci
    join public.branch_product_return_items i on i.id = ci.return_item_id
    join public.purchase_items pi on pi.id = i.purchase_item_id
    where ci.consolidation_id = p_consolidation_id and ci.org_id = p_org_id
    order by i.purchase_item_id
    for update of pi
  loop
    if v_item.purchase_item_id is null or v_item.product_id is distinct from v_item.purchased_product_id then
      raise exception 'A return item does not match its original purchase line';
    end if;
    select coalesce(sum(pri.return_qty), 0) into v_prior_qty
    from public.purchase_return_items pri
    join public.purchase_returns pr on pr.id = pri.return_id
    where pri.purchase_item_id = v_item.purchase_item_id
      and pr.org_id = p_org_id
      and pr.status not in ('draft', 'rejected');
    if v_prior_qty + v_item.return_qty > v_item.quantity_received then
      raise exception 'The supplier return exceeds the remaining purchased quantity';
    end if;
    v_total := v_total + v_item.return_qty * v_item.unit_price;
    insert into public.purchase_return_items (
      return_id, org_id, purchase_item_id, product_id, purchased_qty,
      return_qty, unit_cost, return_value, return_reason, condition
    ) values (
      v_return.id, p_org_id, v_item.purchase_item_id, v_item.product_id,
      v_item.quantity_received, v_item.return_qty, v_item.unit_price,
      v_item.return_qty * v_item.unit_price, v_item.return_reason, v_item.condition
    );
    v_line_count := v_line_count + 1;
  end loop;
  if v_line_count = 0 then raise exception 'The consolidation has no purchase-matched return items'; end if;

  update public.purchase_returns
  set total_return_value = v_total, refund_amount = v_total
  where id = v_return.id;
  update public.branch_product_return_consolidations
  set status = 'supplier_return_created', purchase_return_id = v_return.id
  where id = v_consolidation.id;
  update public.branch_product_returns r
  set status = 'supplier_return_created', updated_at = now()
  where r.id in (
    select i.return_id
    from public.branch_product_return_consolidation_items ci
    join public.branch_product_return_items i on i.id = ci.return_item_id
    where ci.consolidation_id = p_consolidation_id
  )
  and not exists (
    select 1
    from public.branch_product_return_items ri
    left join public.branch_product_return_consolidation_items ci
      on ci.return_item_id = ri.id and ci.org_id = p_org_id
    left join public.branch_product_return_consolidations c
      on c.id = ci.consolidation_id and c.org_id = p_org_id
    where ri.return_id = r.id
      and ri.org_id = p_org_id
      and (c.id is null or c.status not in ('supplier_return_created', 'accepted', 'partially_accepted', 'rejected', 'completed'))
  );
  insert into public.audit_logs (org_id, actor_id, action, entity_type, entity_id, metadata)
  values (
    p_org_id, p_actor_id, 'branch_product_return.supplier_return_created',
    'branch_product_return_consolidations', p_consolidation_id,
    jsonb_build_object(
      'purchase_return_id', v_return.id,
      'purchase_return_number', v_return.return_number,
      'total_return_value', v_total,
      'module', 'return_products'
    )
  );
  return query select v_return.id, v_return.return_number;
end;
$$;

revoke all on function public.create_branch_return_purchase_return(uuid, uuid, uuid) from public, anon, authenticated;
grant execute on function public.create_branch_return_purchase_return(uuid, uuid, uuid) to service_role;

create or replace function public.record_branch_product_supplier_response(
  p_org_id uuid,
  p_actor_id uuid,
  p_consolidation_id uuid,
  p_responses jsonb,
  p_notes text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_consolidation public.branch_product_return_consolidations%rowtype;
  v_line jsonb;
  v_item public.branch_product_return_items%rowtype;
  v_destination_id uuid;
  v_expected_count integer;
  v_response_count integer := 0;
  v_accepted_total integer := 0;
  v_rejected_total integer := 0;
  v_accepted integer;
  v_rejected integer;
  v_purchase_status public.purchase_return_status;
begin
  if auth.role() <> 'service_role' then
    raise exception 'Not authorized to record supplier outcomes';
  end if;
  if not exists (
    select 1 from public.organization_members m
    where m.org_id = p_org_id and m.user_id = p_actor_id
      and m.status = 'active' and m.branch_scope = 'all'
  ) then
    raise exception 'Supplier outcomes are restricted to central organization members';
  end if;
  select * into v_consolidation
  from public.branch_product_return_consolidations
  where id = p_consolidation_id and org_id = p_org_id
  for update;
  if not found or v_consolidation.status <> 'supplier_return_created' or v_consolidation.purchase_return_id is null then
    raise exception 'Create and approve the supplier Purchase Return before recording its outcome';
  end if;
  select status into v_purchase_status
  from public.purchase_returns
  where id = v_consolidation.purchase_return_id and org_id = p_org_id;
  if v_purchase_status is distinct from 'approved' then
    raise exception 'The Purchase Return must be approved before its supplier outcome is recorded';
  end if;
  select count(*) into v_expected_count
  from public.branch_product_return_consolidation_items
  where consolidation_id = p_consolidation_id and org_id = p_org_id;
  if jsonb_typeof(p_responses) <> 'array' or jsonb_array_length(p_responses) <> v_expected_count or v_expected_count = 0 then
    raise exception 'Provide an accepted and rejected quantity for every consolidated item';
  end if;
  select count(distinct value->>'return_item_id') into v_response_count
  from jsonb_array_elements(p_responses);
  if v_response_count <> v_expected_count then
    raise exception 'Supplier response contains duplicate item rows';
  end if;
  v_response_count := 0;

  for v_line in select value from jsonb_array_elements(p_responses)
  loop
    v_accepted := (v_line->>'accepted_quantity')::integer;
    v_rejected := (v_line->>'rejected_quantity')::integer;
    select i.* into v_item
    from public.branch_product_return_items i
    join public.branch_product_return_consolidation_items ci on ci.return_item_id = i.id
    where ci.consolidation_id = p_consolidation_id
      and ci.org_id = p_org_id
      and i.id = (v_line->>'return_item_id')::uuid
    for update of i;
    if not found then raise exception 'A supplier response item is not in this consolidation'; end if;
    if v_accepted < 0 or v_rejected < 0 or v_accepted + v_rejected <> v_item.return_qty then
      raise exception 'Accepted and rejected quantities must match each item return quantity';
    end if;

    update public.branch_product_return_items
    set supplier_accepted_qty = v_accepted,
        supplier_rejected_qty = v_rejected,
        supplier_response_notes = nullif(trim(p_notes), '')
    where id = v_item.id;

    if v_rejected > 0 then
      select destination_location_id into v_destination_id
      from public.branch_product_returns
      where id = v_item.return_id and org_id = p_org_id;
      insert into public.product_stock_levels (org_id, product_id, location_id, quantity)
      values (p_org_id, v_item.product_id, v_destination_id, v_rejected)
      on conflict (product_id, location_id)
      do update set quantity = public.product_stock_levels.quantity + excluded.quantity, updated_at = now();
    end if;
    v_accepted_total := v_accepted_total + v_accepted;
    v_rejected_total := v_rejected_total + v_rejected;
    v_response_count := v_response_count + 1;
  end loop;

  if v_response_count <> v_expected_count then
    raise exception 'Supplier response contains duplicate or missing item rows';
  end if;
  update public.branch_product_return_consolidations
  set status = case
        when v_rejected_total = 0 then 'accepted'
        when v_accepted_total = 0 then 'rejected'
        else 'partially_accepted'
      end,
      supplier_accepted_qty = v_accepted_total,
      supplier_rejected_qty = v_rejected_total,
      supplier_response_notes = nullif(trim(p_notes), ''),
      supplier_responded_by = p_actor_id,
      supplier_responded_at = now()
  where id = p_consolidation_id;

  update public.branch_product_returns r
  set status = 'completed', updated_at = now()
  where r.id in (
    select i.return_id
    from public.branch_product_return_consolidation_items ci
    join public.branch_product_return_items i on i.id = ci.return_item_id
    where ci.consolidation_id = p_consolidation_id
  )
  and not exists (
    select 1 from public.branch_product_return_items i
    left join public.branch_product_return_consolidation_items ci on ci.return_item_id = i.id
    where i.return_id = r.id
      and (ci.return_item_id is null or i.supplier_accepted_qty is null or i.supplier_rejected_qty is null)
  );

  insert into public.audit_logs (org_id, actor_id, action, entity_type, entity_id, metadata)
  values (
    p_org_id, p_actor_id, 'branch_product_return.supplier_response_recorded',
    'branch_product_return_consolidations', p_consolidation_id,
    jsonb_build_object(
      'accepted_quantity', v_accepted_total,
      'rejected_quantity', v_rejected_total,
      'notes', nullif(trim(p_notes), ''),
      'module', 'return_products'
    )
  );
end;
$$;

revoke all on function public.record_branch_product_supplier_response(uuid, uuid, uuid, jsonb, text) from public, anon, authenticated;
grant execute on function public.record_branch_product_supplier_response(uuid, uuid, uuid, jsonb, text) to service_role;

commit;
