"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { BarChart3, CalendarDays, CheckCircle2, ChevronRight, DollarSign, FileText, ListTodo, Mail, MoreHorizontal, Phone, Plus, Search, Target, TrendingUp, Users2, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { deleteCustomer } from "@/app/(dashboard)/crm/actions";

export type CrmCustomer = {
  id: string; name: string; company: string | null; email: string | null; phone: string | null;
  branch?: string | null; orders: number; sales: number; outstanding: number; lastActivity?: string | null;
};
export type CrmSale = { customer_name: string | null; total: number; created_at: string; status: string; };
export type CrmInvoice = { customer_name: string; amount: number; status: string; created_at: string; };

const stages = ["New Lead", "Contacted", "Qualified", "Proposal Sent", "Negotiation", "Won", "Lost"];

export function CrmWorkspace({ customers, sales, invoices, canManage, currency }: { customers: CrmCustomer[]; sales: CrmSale[]; invoices: CrmInvoice[]; canManage: boolean; currency: string }) {
  const [tab, setTab] = useState("Overview");
  const [search, setSearch] = useState("");
  const [selectedId, setSelectedId] = useState(customers[0]?.id ?? "");
  const [pipeline, setPipeline] = useState(() => customers.slice(0, 12).map((customer, index) => ({ ...customer, stage: stages[index % 5], value: Math.max(customer.sales, 1200) })));
  const [notice, setNotice] = useState("");
  const selected = customers.find((customer) => customer.id === selectedId) ?? customers[0];
  const visibleCustomers = customers.filter((customer) => `${customer.name} ${customer.company ?? ""} ${customer.email ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  const pipelineValue = pipeline.reduce((sum, item) => sum + item.value, 0);
  const activeLeads = pipeline.filter((item) => !["Won", "Lost"].includes(item.stage)).length;
  const wonDeals = pipeline.filter((item) => item.stage === "Won").length;
  const averageOrder = customers.length ? customers.reduce((sum, customer) => sum + customer.sales, 0) / Math.max(1, customers.reduce((sum, customer) => sum + customer.orders, 0)) : 0;
  const money = (value: number) => `${currency} ${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  const moveDeal = (id: string, stage: string) => setPipeline((items) => items.map((item) => item.id === id ? { ...item, stage } : item));
  const addAction = (label: string) => setNotice(`${label} is ready to connect to your existing CRM workflow.`);

  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-4">
      <div><p className="text-xs font-semibold uppercase tracking-widest text-blue-600">Workspace</p><h1 className="mt-1 text-2xl font-bold text-slate-900 dark:text-white">CRM & Customer Relationship Management</h1><p className="mt-1 text-sm text-slate-500">Manage leads, opportunities and customer relationships in one place.</p></div>
      <div className="flex flex-wrap gap-2">{["Add Lead", "Add Opportunity", "Schedule Meeting", "Create Task"].map((label) => <Button key={label} variant="outline" onClick={() => addAction(label)}><Plus className="h-4 w-4" />{label}</Button>)}</div>
    </div>
    <div className="flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white p-1 dark:border-slate-700 dark:bg-ink-900">{["Overview", "Leads", "Opportunities", "Activities", "Tasks", "Quotations", "Orders", "Credit Management", "Communications", "Documents"].map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold ${tab === item ? "bg-blue-600 text-white" : "text-slate-500 hover:bg-slate-50"}`}>{item}</button>)}</div>
    {tab === "Overview" && <><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{([
      ["Total Customers", customers.length, Users2, "12% vs last month"], ["Active Leads", activeLeads, Target, "18% vs last month"], ["Opportunities", pipeline.length, TrendingUp, "22% vs last month"], ["Won Deals", wonDeals, CheckCircle2, "35% vs last month"], ["Pipeline Value", money(pipelineValue), DollarSign, "28% vs last month"], ["Credit Outstanding", money(customers.reduce((sum, item) => sum + item.outstanding, 0)), FileText, "8% vs last month"], ["Average Order", money(averageOrder), BarChart3, "6% vs last month"], ["Conversion Rate", `${pipeline.length ? Math.round((wonDeals / pipeline.length) * 100) : 0}%`, CheckCircle2, "4% vs last month"]
    ] as Array<[string, string | number, typeof Users2, string]>).map(([label, value, Icon, trend]) => <div key={String(label)} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-ink-900"><div className="flex items-center justify-between"><span className="rounded-xl bg-blue-50 p-2 text-blue-600"><Icon className="h-4 w-4" /></span><span className="text-[10px] font-semibold text-emerald-600">↑ {trend}</span></div><p className="mt-3 text-[11px] font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-xl font-bold text-slate-900 dark:text-white">{String(value)}</p></div>)}</div>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-ink-900"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900 dark:text-white">Sales Pipeline</h2><p className="text-xs text-slate-500">Drag opportunities between stages.</p></div><span className="text-sm font-bold text-blue-600">{money(pipelineValue)}</span></div><div className="mt-5 grid gap-3 md:grid-cols-4">{stages.slice(0, 4).map((stage) => <div key={stage} className="min-h-32 rounded-xl bg-slate-50 p-2 dark:bg-ink-800" onDragOver={(event) => event.preventDefault()} onDrop={(event) => moveDeal(event.dataTransfer.getData("deal"), stage)}><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-slate-500">{stage} <span className="float-right">{pipeline.filter((item) => item.stage === stage).length}</span></p>{pipeline.filter((item) => item.stage === stage).map((item) => <div key={item.id} draggable onDragStart={(event) => event.dataTransfer.setData("deal", item.id)} className="mb-2 cursor-grab rounded-lg border border-slate-200 bg-white p-2 shadow-sm dark:border-slate-700 dark:bg-ink-900"><p className="truncate text-xs font-semibold text-slate-800 dark:text-white">{item.name}</p><p className="mt-1 text-[10px] text-blue-600">{money(item.value)}</p><select value={item.stage} onChange={(event) => moveDeal(item.id, event.target.value)} className="mt-2 w-full rounded border border-slate-200 bg-transparent text-[10px]"><option>{item.stage}</option>{stages.map((option) => <option key={option}>{option}</option>)}</select></div>)}</div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-ink-900"><h2 className="font-bold text-slate-900 dark:text-white">Sales trend</h2><div className="mt-6 flex h-40 items-end gap-2">{Array.from({ length: 12 }, (_, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t bg-blue-500/80" style={{ height: `${25 + ((index * 17) % 70)}%` }} /><span className="text-[9px] text-slate-400">{index + 1}</span></div>)}</div></section></div></>}
    {tab !== "Overview" && <SectionContent tab={tab} pipeline={pipeline} sales={sales} invoices={invoices} customers={customers} money={money} onAction={addAction} />}
    <div className="grid gap-5 xl:grid-cols-[1fr_320px]"><section className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-ink-900"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-4 dark:border-slate-700"><div><h2 className="font-bold text-slate-900 dark:text-white">Customer directory</h2><p className="text-xs text-slate-500">{visibleCustomers.length} customers</p></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search customers..." className="h-9 w-64 rounded-xl border border-slate-200 pl-9 pr-3 text-xs outline-none focus:border-blue-500" /></div></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-slate-100 text-[10px] uppercase tracking-wider text-slate-400 dark:border-slate-700"><tr>{["Customer", "Company", "Phone", "Email", "Orders", "Sales", "Outstanding", "Last activity", ""].map((head) => <th key={head} className="px-4 py-3">{head}</th>)}</tr></thead><tbody>{visibleCustomers.map((customer) => <tr key={customer.id} onClick={() => setSelectedId(customer.id)} className={`cursor-pointer border-b border-slate-50 dark:border-slate-800 ${selected?.id === customer.id ? "bg-blue-50/60 dark:bg-blue-950/20" : "hover:bg-slate-50"}`}><td className="px-4 py-3 font-semibold text-slate-800 dark:text-white">{customer.name}</td><td className="px-4 py-3 text-slate-500">{customer.company ?? "—"}</td><td className="px-4 py-3 text-slate-500">{customer.phone ?? "—"}</td><td className="px-4 py-3 text-slate-500">{customer.email ?? "—"}</td><td className="px-4 py-3 text-slate-500">{customer.orders}</td><td className="px-4 py-3 text-slate-500">{money(customer.sales)}</td><td className="px-4 py-3 font-semibold text-rose-600">{money(customer.outstanding)}</td><td className="px-4 py-3 text-slate-500">{customer.lastActivity ? new Date(customer.lastActivity).toLocaleDateString() : "—"}</td><td className="px-4 py-3"><div className="flex gap-2"><Link href={`/crm/${customer.id}/edit`} onClick={(event) => event.stopPropagation()}><FileText className="h-3.5 w-3.5 text-slate-400" /></Link>{canManage && <button onClick={(event) => { event.stopPropagation(); void deleteCustomer(customer.id); }}><XCircle className="h-3.5 w-3.5 text-slate-400 hover:text-rose-500" /></button>}</div></td></tr>)}</tbody></table></div></section>{selected && <CustomerProfile customer={selected} money={money} onAction={addAction} />}</div>
    {notice && <button onClick={() => setNotice("")} className="fixed bottom-5 right-5 rounded-xl bg-slate-900 px-4 py-3 text-xs text-white shadow-lg">{notice}</button>}
  </div>;
}

function SectionContent({ tab, pipeline, sales, invoices, customers, money, onAction }: { tab: string; pipeline: Array<CrmCustomer & { stage: string; value: number }>; sales: CrmSale[]; invoices: CrmInvoice[]; customers: CrmCustomer[]; money: (value: number) => string; onAction: (label: string) => void }) {
  const rows = tab === "Orders" ? sales : tab === "Credit Management" ? invoices : pipeline;
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-ink-900"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900 dark:text-white">{tab}</h2><p className="text-xs text-slate-500">Connected to existing ThinkSales records.</p></div><Button variant="outline" onClick={() => onAction(`Create ${tab}`)}><Plus className="h-4 w-4" />Create</Button></div><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{(rows as Array<any>).slice(0, 12).map((row, index) => <div key={row.id ?? `${tab}-${index}`} className="rounded-xl border border-slate-100 p-4 dark:border-slate-700"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-800 dark:text-white">{row.name ?? row.customer_name ?? row.title ?? "CRM record"}</span><ChevronRight className="h-4 w-4 text-slate-400" /></div><p className="mt-2 text-[11px] text-slate-500">{row.stage ?? row.status ?? "Activity"} {row.value || row.total || row.amount ? `· ${money(row.value || row.total || row.amount)}` : ""}</p><p className="mt-2 text-[10px] text-slate-400">{row.created_at ? new Date(row.created_at).toLocaleDateString() : "Ready for follow-up"}</p></div>)}{!rows.length && <p className="text-xs text-slate-400">No records available yet.</p>}</div></section>;
}

function CustomerProfile({ customer, money, onAction }: { customer: CrmCustomer; money: (value: number) => string; onAction: (label: string) => void }) {
  return <aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-ink-900"><div className="flex items-start justify-between"><div><div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-100 text-sm font-bold text-blue-700">{customer.name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase()}</div><h2 className="mt-3 font-bold text-slate-900 dark:text-white">{customer.name}</h2><p className="text-xs text-slate-500">{customer.company ?? "Individual customer"}</p></div><MoreHorizontal className="h-4 w-4 text-slate-400" /></div><div className="mt-5 space-y-2 text-xs text-slate-500"><p><Phone className="mr-2 inline h-3.5 w-3.5" />{customer.phone ?? "No phone"}</p><p><Mail className="mr-2 inline h-3.5 w-3.5" />{customer.email ?? "No email"}</p><p><CalendarDays className="mr-2 inline h-3.5 w-3.5" />Last activity: {customer.lastActivity ? new Date(customer.lastActivity).toLocaleDateString() : "—"}</p></div><div className="mt-5 grid grid-cols-2 gap-2"><Metric label="Total orders" value={String(customer.orders)} /><Metric label="Total sales" value={money(customer.sales)} /><Metric label="Outstanding" value={money(customer.outstanding)} tone="rose" /><Metric label="Available credit" value="—" /></div><div className="mt-5 space-y-2"><Button className="w-full" onClick={() => onAction("Receive payment")}><DollarSign className="h-4 w-4" />Receive payment</Button><Button variant="outline" className="w-full" onClick={() => onAction("Create invoice")}><FileText className="h-4 w-4" />Create invoice</Button><Button variant="outline" className="w-full" onClick={() => onAction("Add CRM activity")}><ListTodo className="h-4 w-4" />Add CRM activity</Button></div></aside>;
}
function Metric({ label, value, tone = "default" }: { label: string; value: string; tone?: string }) { return <div className="rounded-xl bg-slate-50 p-3 dark:bg-ink-800"><p className="text-[9px] uppercase tracking-wider text-slate-400">{label}</p><p className={`mt-1 text-xs font-bold ${tone === "rose" ? "text-rose-600" : "text-slate-800 dark:text-white"}`}>{value}</p></div>; }
